#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

#define ABILITY_NONE 0
#define ABILITY_STENCH 1
#define ABILITY_DRIZZLE 2
#define ABILITY_SPEED_BOOST 3
#define ABILITY_BATTLE_ARMOR 4
#define ABILITY_STURDY 5
#define ABILITY_DAMP 6
#define ABILITY_LIMBER 7
#define ABILITY_SAND_VEIL 8
#define ABILITY_STATIC 9
#define ABILITY_VOLT_ABSORB 10
#define ABILITY_WATER_ABSORB 11
#define ABILITY_OBLIVIOUS 12
#define ABILITY_CLOUD_NINE 13
#define ABILITY_COMPOUND_EYES 14
#define ABILITY_INSOMNIA 15
#define ABILITY_COLOR_CHANGE 16
#define ABILITY_IMMUNITY 17
#define ABILITY_FLASH_FIRE 18
#define ABILITY_SHIELD_DUST 19
#define ABILITY_OWN_TEMPO 20
#define ABILITY_SUCTION_CUPS 21
#define ABILITY_INTIMIDATE 22
#define ABILITY_SHADOW_TAG 23
#define ABILITY_ROUGH_SKIN 24
#define ABILITY_WONDER_GUARD 25
#define ABILITY_LEVITATE 26
#define ABILITY_EFFECT_SPORE 27
#define ABILITY_SYNCHRONIZE 28
#define ABILITY_CLEAR_BODY 29
#define ABILITY_NATURAL_CURE 30
#define ABILITY_LIGHTNING_ROD 31
#define ABILITY_SERENE_GRACE 32
#define ABILITY_SWIFT_SWIM 33
#define ABILITY_CHLOROPHYLL 34
#define ABILITY_ILLUMINATE 35
#define ABILITY_TRACE 36
#define ABILITY_HUGE_POWER 37
#define ABILITY_POISON_POINT 38
#define ABILITY_INNER_FOCUS 39
#define ABILITY_MAGMA_ARMOR 40
#define ABILITY_WATER_VEIL 41
#define ABILITY_MAGNET_PULL 42
#define ABILITY_SOUNDPROOF 43
#define ABILITY_RAIN_DISH 44
#define ABILITY_SAND_STREAM 45
#define ABILITY_PRESSURE 46
#define ABILITY_THICK_FAT 47
#define ABILITY_EARLY_BIRD 48
#define ABILITY_FLAME_BODY 49
#define ABILITY_RUN_AWAY 50
#define ABILITY_KEEN_EYE 51
#define ABILITY_HYPER_CUTTER 52
#define ABILITY_PICKUP 53
#define ABILITY_TRUANT 54
#define ABILITY_HUSTLE 55
#define ABILITY_CUTE_CHARM 56
#define ABILITY_PLUS 57
#define ABILITY_MINUS 58
#define ABILITY_FORECAST 59
#define ABILITY_STICKY_HOLD 60
#define ABILITY_SHED_SKIN 61
#define ABILITY_GUTS 62
#define ABILITY_MARVEL_SCALE 63
#define ABILITY_LIQUID_OOZE 64
#define ABILITY_OVERGROW 65
#define ABILITY_BLAZE 66
#define ABILITY_TORRENT 67
#define ABILITY_SWARM 68
#define ABILITY_ROCK_HEAD 69
#define ABILITY_DROUGHT 70
#define ABILITY_ARENA_TRAP 71
#define ABILITY_VITAL_SPIRIT 72
#define ABILITY_WHITE_SMOKE 73
#define ABILITY_PURE_POWER 74
#define ABILITY_SHELL_ARMOR 75
#define ABILITY_AIR_LOCK 76

#define ABILITIES_COUNT_GEN3 77

// Gen 4
#define ABILITY_TANGLED_FEET 77
#define ABILITY_MOTOR_DRIVE 78
#define ABILITY_RIVALRY 79
#define ABILITY_STEADFAST 80
#define ABILITY_SNOW_CLOAK 81
#define ABILITY_GLUTTONY 82
#define ABILITY_ANGER_POINT 83
#define ABILITY_UNBURDEN 84
#define ABILITY_HEATPROOF 85
#define ABILITY_SIMPLE 86
#define ABILITY_DRY_SKIN 87
#define ABILITY_DOWNLOAD 88
#define ABILITY_IRON_FIST 89
#define ABILITY_POISON_HEAL 90
#define ABILITY_ADAPTABILITY 91
#define ABILITY_SKILL_LINK 92
#define ABILITY_HYDRATION 93
#define ABILITY_SOLAR_POWER 94
#define ABILITY_QUICK_FEET 95
#define ABILITY_NORMALIZE 96
#define ABILITY_SNIPER 97
#define ABILITY_MAGIC_GUARD 98
#define ABILITY_NO_GUARD 99
#define ABILITY_STALL 100
#define ABILITY_TECHNICIAN 101
#define ABILITY_LEAF_GUARD 102
#define ABILITY_KLUTZ 103
#define ABILITY_MOLD_BREAKER 104
#define ABILITY_SUPER_LUCK 105
#define ABILITY_AFTERMATH 106
#define ABILITY_ANTICIPATION 107
#define ABILITY_FOREWARN 108
#define ABILITY_UNAWARE 109
#define ABILITY_TINTED_LENS 110
#define ABILITY_FILTER 111
#define ABILITY_SLOW_START 112
#define ABILITY_SCRAPPY 113
#define ABILITY_STORM_DRAIN 114
#define ABILITY_ICE_BODY 115
#define ABILITY_SOLID_ROCK 116
#define ABILITY_SNOW_WARNING 117
#define ABILITY_HONEY_GATHER 118
#define ABILITY_FRISK 119
#define ABILITY_RECKLESS 120
#define ABILITY_MULTITYPE 121
#define ABILITY_FLOWER_GIFT 122
#define ABILITY_BAD_DREAMS 123

#define ABILITIES_COUNT_GEN4 124

// Gen 5
#define ABILITY_PICKPOCKET 124
#define ABILITY_SHEER_FORCE 125
#define ABILITY_CONTRARY 126
#define ABILITY_UNNERVE 127
#define ABILITY_DEFIANT 128
#define ABILITY_DEFEATIST 129
#define ABILITY_CURSED_BODY 130
#define ABILITY_HEALER 131
#define ABILITY_FRIEND_GUARD 132
#define ABILITY_WEAK_ARMOR 133
#define ABILITY_HEAVY_METAL 134
#define ABILITY_LIGHT_METAL 135
#define ABILITY_MULTISCALE 136
#define ABILITY_TOXIC_BOOST 137
#define ABILITY_FLARE_BOOST 138
#define ABILITY_HARVEST 139
#define ABILITY_TELEPATHY 140
#define ABILITY_MOODY 141
#define ABILITY_OVERCOAT 142
#define ABILITY_POISON_TOUCH 143
#define ABILITY_REGENERATOR 144
#define ABILITY_BIG_PECKS 145
#define ABILITY_SAND_RUSH 146
#define ABILITY_WONDER_SKIN 147
#define ABILITY_ANALYTIC 148
#define ABILITY_ILLUSION 149
#define ABILITY_IMPOSTER 150
#define ABILITY_INFILTRATOR 151
#define ABILITY_MUMMY 152
#define ABILITY_MOXIE 153
#define ABILITY_JUSTIFIED 154
#define ABILITY_RATTLED 155
#define ABILITY_MAGIC_BOUNCE 156
#define ABILITY_SAP_SIPPER 157
#define ABILITY_PRANKSTER 158
#define ABILITY_SAND_FORCE 159
#define ABILITY_IRON_BARBS 160
#define ABILITY_ZEN_MODE 161
#define ABILITY_VICTORY_STAR 162
#define ABILITY_TURBOBLAZE 163
#define ABILITY_TERAVOLT 164

#define ABILITIES_COUNT_GEN5 165

// Gen 6
#define ABILITY_AROMA_VEIL 165
#define ABILITY_FLOWER_VEIL 166
#define ABILITY_CHEEK_POUCH 167
#define ABILITY_PROTEAN 168
#define ABILITY_FUR_COAT 169
#define ABILITY_MAGICIAN 170
#define ABILITY_BULLETPROOF 171
#define ABILITY_COMPETITIVE 172
#define ABILITY_STRONG_JAW 173
#define ABILITY_REFRIGERATE 174
#define ABILITY_SWEET_VEIL 175
#define ABILITY_STANCE_CHANGE 176
#define ABILITY_GALE_WINGS 177
#define ABILITY_MEGA_LAUNCHER 178
#define ABILITY_GRASS_PELT 179
#define ABILITY_SYMBIOSIS 180
#define ABILITY_TOUGH_CLAWS 181
#define ABILITY_PIXILATE 182
#define ABILITY_GOOEY 183
#define ABILITY_AERILATE 184
#define ABILITY_PARENTAL_BOND 185
#define ABILITY_DARK_AURA 186
#define ABILITY_FAIRY_AURA 187
#define ABILITY_AURA_BREAK 188
#define ABILITY_PRIMORDIAL_SEA 189
#define ABILITY_DESOLATE_LAND 190
#define ABILITY_DELTA_STREAM 191

#define ABILITIES_COUNT_GEN6 192

// Gen 7
#define ABILITY_STAMINA 192
#define ABILITY_WIMP_OUT 193
#define ABILITY_EMERGENCY_EXIT 194
#define ABILITY_WATER_COMPACTION 195
#define ABILITY_MERCILESS 196
#define ABILITY_SHIELDS_DOWN 197
#define ABILITY_STAKEOUT 198
#define ABILITY_WATER_BUBBLE 199
#define ABILITY_STEELWORKER 200
#define ABILITY_BERSERK 201
#define ABILITY_SLUSH_RUSH 202
#define ABILITY_LONG_REACH 203
#define ABILITY_LIQUID_VOICE 204
#define ABILITY_TRIAGE 205
#define ABILITY_GALVANIZE 206
#define ABILITY_SURGE_SURFER 207
#define ABILITY_SCHOOLING 208
#define ABILITY_DISGUISE 209
#define ABILITY_BATTLE_BOND 210
#define ABILITY_POWER_CONSTRUCT 211
#define ABILITY_CORROSION 212
#define ABILITY_COMATOSE 213
#define ABILITY_QUEENLY_MAJESTY 214
#define ABILITY_INNARDS_OUT 215
#define ABILITY_DANCER 216
#define ABILITY_BATTERY 217
#define ABILITY_FLUFFY 218
#define ABILITY_DAZZLING 219
#define ABILITY_SOUL_HEART 220
#define ABILITY_TANGLING_HAIR 221
#define ABILITY_RECEIVER 222
#define ABILITY_POWER_OF_ALCHEMY 223
#define ABILITY_BEAST_BOOST 224
#define ABILITY_RKS_SYSTEM 225
#define ABILITY_ELECTRIC_SURGE 226
#define ABILITY_PSYCHIC_SURGE 227
#define ABILITY_MISTY_SURGE 228
#define ABILITY_GRASSY_SURGE 229
#define ABILITY_FULL_METAL_BODY 230
#define ABILITY_SHADOW_SHIELD 231
#define ABILITY_PRISM_ARMOR 232
#define ABILITY_NEUROFORCE 233

#define ABILITIES_COUNT_GEN7 234

// Gen 8
#define ABILITY_INTREPID_SWORD 234
#define ABILITY_DAUNTLESS_SHIELD 235
#define ABILITY_LIBERO 236
#define ABILITY_BALL_FETCH 237
#define ABILITY_COTTON_DOWN 238
#define ABILITY_PROPELLER_TAIL 239
#define ABILITY_MIRROR_ARMOR 240
#define ABILITY_GULP_MISSILE 241
#define ABILITY_STALWART 242
#define ABILITY_STEAM_ENGINE 243
#define ABILITY_PUNK_ROCK 244
#define ABILITY_SAND_SPIT 245
#define ABILITY_ICE_SCALES 246
#define ABILITY_RIPEN 247
#define ABILITY_ICE_FACE 248
#define ABILITY_POWER_SPOT 249
#define ABILITY_MIMICRY 250
#define ABILITY_SCREEN_CLEANER 251
#define ABILITY_STEELY_SPIRIT 252
#define ABILITY_PERISH_BODY 253
#define ABILITY_WANDERING_SPIRIT 254
#define ABILITY_GORILLA_TACTICS 255
#define ABILITY_NEUTRALIZING_GAS 256
#define ABILITY_PASTEL_VEIL 257
#define ABILITY_HUNGER_SWITCH 258
#define ABILITY_QUICK_DRAW 259
#define ABILITY_UNSEEN_FIST 260
#define ABILITY_CURIOUS_MEDICINE 261
#define ABILITY_TRANSISTOR 262
#define ABILITY_DRAGONS_MAW 263
#define ABILITY_CHILLING_NEIGH 264
#define ABILITY_GRIM_NEIGH 265
#define ABILITY_AS_ONE_ICE_RIDER 266
#define ABILITY_AS_ONE_SHADOW_RIDER 267

#define ABILITIES_COUNT_GEN8 268

// Gen 9
#define ABILITY_LINGERING_AROMA 268
#define ABILITY_SEED_SOWER 269
#define ABILITY_THERMAL_EXCHANGE 270
#define ABILITY_ANGER_SHELL 271
#define ABILITY_PURIFYING_SALT 272
#define ABILITY_WELL_BAKED_BODY 273
#define ABILITY_WIND_RIDER 274
#define ABILITY_GUARD_DOG 275
#define ABILITY_ROCKY_PAYLOAD 276
#define ABILITY_WIND_POWER 277
#define ABILITY_ZERO_TO_HERO 278
#define ABILITY_COMMANDER 279
#define ABILITY_ELECTROMORPHOSIS 280
#define ABILITY_PROTOSYNTHESIS 281
#define ABILITY_QUARK_DRIVE 282
#define ABILITY_GOOD_AS_GOLD 283
#define ABILITY_VESSEL_OF_RUIN 284
#define ABILITY_SWORD_OF_RUIN 285
#define ABILITY_TABLETS_OF_RUIN 286
#define ABILITY_BEADS_OF_RUIN 287
#define ABILITY_ORICHALCUM_PULSE 288
#define ABILITY_HADRON_ENGINE 289
#define ABILITY_OPPORTUNIST 290
#define ABILITY_CUD_CHEW 291
#define ABILITY_SHARPNESS 292
#define ABILITY_SUPREME_OVERLORD 293
#define ABILITY_COSTAR 294
#define ABILITY_TOXIC_DEBRIS 295
#define ABILITY_ARMOR_TAIL 296
#define ABILITY_EARTH_EATER 297
#define ABILITY_MYCELIUM_MIGHT 298
#define ABILITY_HOSPITALITY 299
#define ABILITY_MINDS_EYE 300
#define ABILITY_EMBODY_ASPECT_TEAL 301
#define ABILITY_EMBODY_ASPECT_HEARTHFLAME 302
#define ABILITY_EMBODY_ASPECT_WELLSPRING 303
#define ABILITY_EMBODY_ASPECT_CORNERSTONE 304
#define ABILITY_TOXIC_CHAIN 305
#define ABILITY_SUPERSWEET_SYRUP 306
#define ABILITY_TERA_SHIFT 307
#define ABILITY_TERA_SHELL 308
#define ABILITY_TERAFORM_ZERO 309
#define ABILITY_POISON_PUPPETEER 310
#define ABILITY_MEGA_SOL 311
#define ABILITY_PIERCING_DRILL 312
#define ABILITY_SPICY_SPRAY 313
#define ABILITY_EELEVATE 314
#define ABILITY_FIRE_MANE 315

#define ABILITIES_COUNT_GEN9 316

#define ABILITIES_COUNT_CUSTOM              (ABILITIES_COUNT_GEN9)

// Custom Abilities
#define ABILITY_FLOCK                       (ABILITIES_COUNT_CUSTOM + 0)
#define ABILITY_SHORT_CIRCUIT               (ABILITIES_COUNT_CUSTOM + 1)
#define ABILITY_RAMPAGE                     (ABILITIES_COUNT_CUSTOM + 2)
#define ABILITY_LET_IT_RIP                  (ABILITIES_COUNT_CUSTOM + 3)
#define ABILITY_HIGH_VOLTAGE                (ABILITIES_COUNT_CUSTOM + 4)
#define ABILITY_PERMAFROST                  (ABILITIES_COUNT_CUSTOM + 5)
#define ABILITY_PRECISE_FIST                (ABILITIES_COUNT_CUSTOM + 6)
#define ABILITY_HEARTBREAKER                (ABILITIES_COUNT_CUSTOM + 7)
#define ABILITY_HYDRATE                     (ABILITIES_COUNT_CUSTOM + 8)
#define ABILITY_BURNATE                     (ABILITIES_COUNT_CUSTOM + 9)
#define ABILITY_GROUNDATE                   (ABILITIES_COUNT_CUSTOM + 10)
#define ABILITY_ADAPTATION                  (ABILITIES_COUNT_CUSTOM + 11)
#define ABILITY_AIRBOURNE_STYLE             (ABILITIES_COUNT_CUSTOM + 12)
#define ABILITY_AERODYNAMICS                (ABILITIES_COUNT_CUSTOM + 13)
#define ABILITY_ARTILLERY                   (ABILITIES_COUNT_CUSTOM + 14)
#define ABILITY_AVENGER                     (ABILITIES_COUNT_CUSTOM + 15)
#define ABILITY_BAD_LUCK                    (ABILITIES_COUNT_CUSTOM + 16)
#define ABILITY_BEDOUIN                     (ABILITIES_COUNT_CUSTOM + 17)
#define ABILITY_BATTLE_FURY                 (ABILITIES_COUNT_CUSTOM + 18)
#define ABILITY_BURNING_SURGE               (ABILITIES_COUNT_CUSTOM + 19)
#define ABILITY_CARNIVOROUS                 (ABILITIES_COUNT_CUSTOM + 20)
#define ABILITY_BIG_LEAVES                  (ABILITIES_COUNT_CUSTOM + 21)
#define ABILITY_CURSE_SURGE                 (ABILITIES_COUNT_CUSTOM + 22)
#define ABILITY_EXPERTISE                   (ABILITIES_COUNT_CUSTOM + 23)
#define ABILITY_FROSTBITE                   (ABILITIES_COUNT_CUSTOM + 24)
#define ABILITY_FULL_BELLY                  (ABILITIES_COUNT_CUSTOM + 25)
#define ABILITY_HANGRY_MODE                 (ABILITIES_COUNT_CUSTOM + 26)
#define ABILITY_GIANT_WINGS                 (ABILITIES_COUNT_CUSTOM + 27)
#define ABILITY_HIBERNATE                   (ABILITIES_COUNT_CUSTOM + 28)
#define ABILITY_ICE_DEW                     (ABILITIES_COUNT_CUSTOM + 29)
#define ABILITY_ICE_SLIDING                 (ABILITIES_COUNT_CUSTOM + 30)
#define ABILITY_JUSTICE                     (ABILITIES_COUNT_CUSTOM + 31)
#define ABILITY_LEAD_COAT                   (ABILITIES_COUNT_CUSTOM + 32)
#define ABILITY_LAVAL_BODY                  (ABILITIES_COUNT_CUSTOM + 33)
#define ABILITY_MAGNET_FIELD                (ABILITIES_COUNT_CUSTOM + 34)
#define ABILITY_MOMENTUM                    (ABILITIES_COUNT_CUSTOM + 35)
#define ABILITY_MULTI_LIMBS                 (ABILITIES_COUNT_CUSTOM + 36)
#define ABILITY_PHANTOM                     (ABILITIES_COUNT_CUSTOM + 37)
#define ABILITY_PSY_BARRIER                 (ABILITIES_COUNT_CUSTOM + 38)
#define ABILITY_NIMBLE_FIST                 (ABILITIES_COUNT_CUSTOM + 39)
#define ABILITY_SOIL_ROOT                   (ABILITIES_COUNT_CUSTOM + 40)
#define ABILITY_SANDY_SURGE                 (ABILITIES_COUNT_CUSTOM + 41)
#define ABILITY_FORTITUDE                   (ABILITIES_COUNT_CUSTOM + 42)
#define ABILITY_DREAMCATCHER                (ABILITIES_COUNT_CUSTOM + 43)
#define ABILITY_JUGGERNAUT                  (ABILITIES_COUNT_CUSTOM + 44)
#define ABILITY_WEAKNESS_EXPLOIT            (ABILITIES_COUNT_CUSTOM + 45)
#define ABILITY_SOLENOGLYPHS                (ABILITIES_COUNT_CUSTOM + 46)
#define ABILITY_LEECH_FANGS                 (ABILITIES_COUNT_CUSTOM + 47)
#define ABILITY_SCAVENGER                   (ABILITIES_COUNT_CUSTOM + 48)
#define ABILITY_NOCTURNAL                   (ABILITIES_COUNT_CUSTOM + 49)
#define ABILITY_ETHEREAL                    (ABILITIES_COUNT_CUSTOM + 50)
#define ABILITY_OVERWHELM                   (ABILITIES_COUNT_CUSTOM + 51)
#define ABILITY_IMPENETRABLE                (ABILITIES_COUNT_CUSTOM + 52)
#define ABILITY_WAVE_SURF                   (ABILITIES_COUNT_CUSTOM + 53)
#define ABILITY_RAGING_STORM                (ABILITIES_COUNT_CUSTOM + 54)
#define ABILITY_IRONCLAD_KEEL               (ABILITIES_COUNT_CUSTOM + 55)
#define ABILITY_THICK_FLOSS                 (ABILITIES_COUNT_CUSTOM + 56)
#define ABILITY_LARGE_PETAL                 (ABILITIES_COUNT_CUSTOM + 57)
#define ABILITY_GRIP_PINCER                 (ABILITIES_COUNT_CUSTOM + 58)
#define ABILITY_FOSSILIZED                  (ABILITIES_COUNT_CUSTOM + 59)
#define ABILITY_SPEED_FORCE                 (ABILITIES_COUNT_CUSTOM + 60)
#define ABILITY_MAJESTIC_BIRD               (ABILITIES_COUNT_CUSTOM + 61)
#define ABILITY_COLD_SNAP                   (ABILITIES_COUNT_CUSTOM + 62)
#define ABILITY_NORTH_WIND                  (ABILITIES_COUNT_CUSTOM + 63)
#define ABILITY_POISON_ABSORB               (ABILITIES_COUNT_CUSTOM + 64)
#define ABILITY_PSYCHIC_BARRIER             (ABILITIES_COUNT_CUSTOM + 65)
#define ABILITY_SEA_GUARDIAN                (ABILITIES_COUNT_CUSTOM + 66)
#define ABILITY_SKY_GUARDIAN                (ABILITIES_COUNT_CUSTOM + 67)
#define ABILITY_SPATIAL_WARP                (ABILITIES_COUNT_CUSTOM + 68)
#define ABILITY_TEMPORAL_FLOW               (ABILITIES_COUNT_CUSTOM + 69)
#define ABILITY_BLOOD_LUST                  (ABILITIES_COUNT_CUSTOM + 70)
#define ABILITY_HEADACHE                    (ABILITIES_COUNT_CUSTOM + 71)
#define ABILITY_FIGHTING_SPIRIT             (ABILITIES_COUNT_CUSTOM + 72)
#define ABILITY_NULLIFY                     (ABILITIES_COUNT_CUSTOM + 73)
#define ABILITY_PSYCHIC_MIND                (ABILITIES_COUNT_CUSTOM + 74)
#define ABILITY_UNDYING                     (ABILITIES_COUNT_CUSTOM + 75)
#define ABILITY_SHALLOW_DIVER               (ABILITIES_COUNT_CUSTOM + 76)
#define ABILITY_MULTI_HEADED                (ABILITIES_COUNT_CUSTOM + 77)
#define ABILITY_POISONATE                   (ABILITIES_COUNT_CUSTOM + 78)
#define ABILITY_AMPLIFIER                   (ABILITIES_COUNT_CUSTOM + 79)
#define ABILITY_SEAWEED                     (ABILITIES_COUNT_CUSTOM + 80)
#define ABILITY_PETRIFIED_WOOD              (ABILITIES_COUNT_CUSTOM + 81)
#define ABILITY_PRESENCE_AURA               (ABILITIES_COUNT_CUSTOM + 82)
#define ABILITY_NINJA_STYLE                 (ABILITIES_COUNT_CUSTOM + 83)
#define ABILITY_PORTAL_HOOP                 (ABILITIES_COUNT_CUSTOM + 84)
#define ABILITY_WEATHERCAST                 (ABILITIES_COUNT_CUSTOM + 85)
#define ABILITY_WEATHER_CONTROL             (ABILITIES_COUNT_CUSTOM + 86)
#define ABILITY_PEEK_A_BOO                  (ABILITIES_COUNT_CUSTOM + 87)
#define ABILITY_LOOSING_QUILLS              (ABILITIES_COUNT_CUSTOM + 88)
#define ABILITY_FIELD_EXPLORER              (ABILITIES_COUNT_CUSTOM + 89)
#define ABILITY_AMPHIBIOUS                  (ABILITIES_COUNT_CUSTOM + 90)
#define ABILITY_KINGS_GRACE                 (ABILITIES_COUNT_CUSTOM + 91)
#define ABILITY_SPIDER_LAIR                 (ABILITIES_COUNT_CUSTOM + 92)
#define ABILITY_MAGICAL_DUST                (ABILITIES_COUNT_CUSTOM + 93)
#define ABILITY_DRAGONFLY                   (ABILITIES_COUNT_CUSTOM + 94)
#define ABILITY_AQUATIC                     (ABILITIES_COUNT_CUSTOM + 95)
#define ABILITY_LOUD_BANG                   (ABILITIES_COUNT_CUSTOM + 96)
#define ABILITY_COMMENSALISM                (ABILITIES_COUNT_CUSTOM + 97)
#define ABILITY_HEAVYWEIGHT                 (ABILITIES_COUNT_CUSTOM + 98)
#define ABILITY_BULLS_EYE                   (ABILITIES_COUNT_CUSTOM + 99)
#define ABILITY_MILK_MILKY                  (ABILITIES_COUNT_CUSTOM + 100)
#define ABILITY_LITTERING                   (ABILITIES_COUNT_CUSTOM + 101)
#define ABILITY_UNITY                       (ABILITIES_COUNT_CUSTOM + 102)
#define ABILITY_SWEET_DREAMS                (ABILITIES_COUNT_CUSTOM + 103)
#define ABILITY_VENOMOUS_SURGE              (ABILITIES_COUNT_CUSTOM + 104)
#define ABILITY_RAVINE_SURGE                (ABILITIES_COUNT_CUSTOM + 105)
#define ABILITY_SWAMP_SURGE                 (ABILITIES_COUNT_CUSTOM + 106)
#define ABILITY_FROZEN_SURGE                (ABILITIES_COUNT_CUSTOM + 107)
#define ABILITY_CHRISTMAS_SPIRIT            (ABILITIES_COUNT_CUSTOM + 108)
#define ABILITY_LIQUIFIED                   (ABILITIES_COUNT_CUSTOM + 109)
#define ABILITY_CHARGE_ATTACK               (ABILITIES_COUNT_CUSTOM + 110)
#define ABILITY_SUBTERRANEAN                (ABILITIES_COUNT_CUSTOM + 111)
#define ABILITY_BIRDS_OF_PREY               (ABILITIES_COUNT_CUSTOM + 112)
#define ABILITY_ELECTRIC_BURST              (ABILITIES_COUNT_CUSTOM + 113)
#define ABILITY_ABYSSAL_VOYAGER             (ABILITIES_COUNT_CUSTOM + 114)
#define ABILITY_CAMOUFLAGE                  (ABILITIES_COUNT_CUSTOM + 115)
#define ABILITY_INFLATABLE                  (ABILITIES_COUNT_CUSTOM + 116)
#define ABILITY_DISTORTION_WORLD            (ABILITIES_COUNT_CUSTOM + 117)
#define ABILITY_COIL_UP                     (ABILITIES_COUNT_CUSTOM + 118)
#define ABILITY_CINDER                      (ABILITIES_COUNT_CUSTOM + 119)
#define ABILITY_WATCHDOG                    (ABILITIES_COUNT_CUSTOM + 120)
#define ABILITY_SHOCK_ABSORTION             (ABILITIES_COUNT_CUSTOM + 121)
#define ABILITY_HAUNTED_SPIRIT              (ABILITIES_COUNT_CUSTOM + 122)
#define ABILITY_POWER_MODULATION            (ABILITIES_COUNT_CUSTOM + 123)
#define ABILITY_BLADEMASTER                 (ABILITIES_COUNT_CUSTOM + 124)
#define ABILITY_SAND_PLOW                   (ABILITIES_COUNT_CUSTOM + 125)
#define ABILITY_DESERT_SPIRIT               (ABILITIES_COUNT_CUSTOM + 126)
#define ABILITY_GROWING_TOOTH               (ABILITIES_COUNT_CUSTOM + 127)
#define ABILITY_ANCIENT_IDOL                (ABILITIES_COUNT_CUSTOM + 128)
#define ABILITY_ELECTROCYTES                (ABILITIES_COUNT_CUSTOM + 129)
#define ABILITY_MAJESTIC_MOTH               (ABILITIES_COUNT_CUSTOM + 130)
#define ABILITY_AURORA_BOREALIS             (ABILITIES_COUNT_CUSTOM + 131)
#define ABILITY_CRYSTALLIZE                 (ABILITIES_COUNT_CUSTOM + 132)
#define ABILITY_FRIGHTEN                    (ABILITIES_COUNT_CUSTOM + 133)
#define ABILITY_HYPNOTIST                   (ABILITIES_COUNT_CUSTOM + 134)
#define ABILITY_TOP_SPIN                    (ABILITIES_COUNT_CUSTOM + 135)
#define ABILITY_REFRACTION                  (ABILITIES_COUNT_CUSTOM + 136)
#define ABILITY_MIND_GAME                   (ABILITIES_COUNT_CUSTOM + 137)
#define ABILITY_AIR_BLOWER                  (ABILITIES_COUNT_CUSTOM + 138)
#define ABILITY_EARTHBOUND                  (ABILITIES_COUNT_CUSTOM + 139)
#define ABILITY_SOUL_EATER                  (ABILITIES_COUNT_CUSTOM + 140)
#define ABILITY_SHIELD_WALL                 (ABILITIES_COUNT_CUSTOM + 141)
#define ABILITY_DUAL_WIELDING               (ABILITIES_COUNT_CUSTOM + 142)
#define ABILITY_CORE_EXPOSURE               (ABILITIES_COUNT_CUSTOM + 143)
#define ABILITY_HALF_DRAKE                  (ABILITIES_COUNT_CUSTOM + 144)
#define ABILITY_HALF_DINO                   (ABILITIES_COUNT_CUSTOM + 145)
#define ABILITY_MUSCLE_GAUGE                (ABILITIES_COUNT_CUSTOM + 146)
#define ABILITY_TWISTED_DIMENSION           (ABILITIES_COUNT_CUSTOM + 147)
#define ABILITY_MOLTEN_DOWN                 (ABILITIES_COUNT_CUSTOM + 148)
#define ABILITY_CLAIRVOYANT                 (ABILITIES_COUNT_CUSTOM + 149)
#define ABILITY_MYSTIC_POWER                (ABILITIES_COUNT_CUSTOM + 150)
#define ABILITY_LIVID_SHADOW                (ABILITIES_COUNT_CUSTOM + 151)
#define ABILITY_DEATHLY_EMBRACE             (ABILITIES_COUNT_CUSTOM + 152)
#define ABILITY_MALEFICENT                  (ABILITIES_COUNT_CUSTOM + 153)
#define ABILITY_FIREBRINGER                 (ABILITIES_COUNT_CUSTOM + 154)
#define ABILITY_DRAGONSLAYER                (ABILITIES_COUNT_CUSTOM + 155)
#define ABILITY_REWIND                      (ABILITIES_COUNT_CUSTOM + 156)
#define ABILITY_ANTARCTIC_BIRD              (ABILITIES_COUNT_CUSTOM + 157)
#define ABILITY_PERFECTIONIST               (ABILITIES_COUNT_CUSTOM + 158)
#define ABILITY_CELL_DIVISION               (ABILITIES_COUNT_CUSTOM + 159)
#define ABILITY_PSYCHO_SPIRAL               (ABILITIES_COUNT_CUSTOM + 160)
#define ABILITY_DARK_FLAMES                 (ABILITIES_COUNT_CUSTOM + 161)
#define ABILITY_SHARP_BLADES                (ABILITIES_COUNT_CUSTOM + 162)
#define ABILITY_BULLDOZER                   (ABILITIES_COUNT_CUSTOM + 163)
#define ABILITY_ROYAL_JELLY                 (ABILITIES_COUNT_CUSTOM + 164)
#define ABILITY_POWER_CORE                  (ABILITIES_COUNT_CUSTOM + 165)
#define ABILITY_STRETCHING_TONGUE           (ABILITIES_COUNT_CUSTOM + 166)
#define ABILITY_ANTEATER                    (ABILITIES_COUNT_CUSTOM + 167)
#define ABILITY_TRENCH                      (ABILITIES_COUNT_CUSTOM + 168)
#define ABILITY_GRAVITON_RAY                (ABILITIES_COUNT_CUSTOM + 169)
#define ABILITY_FORCE_OF_NATURE             (ABILITIES_COUNT_CUSTOM + 170)
#define ABILITY_BEWITCHING                  (ABILITIES_COUNT_CUSTOM + 171)
#define ABILITY_AFTERSHOCK                  (ABILITIES_COUNT_CUSTOM + 172)
#define ABILITY_SOLAR_FLARE                 (ABILITIES_COUNT_CUSTOM + 173)
#define ABILITY_LUNAR_ECLIPSE               (ABILITIES_COUNT_CUSTOM + 174)
#define ABILITY_SUGAR_RUSH                  (ABILITIES_COUNT_CUSTOM + 175)
#define ABILITY_POSSESSED                   (ABILITIES_COUNT_CUSTOM + 176)
#define ABILITY_YUKI_ONNA                   (ABILITIES_COUNT_CUSTOM + 177)
#define ABILITY_SIGHTING_SYSTEM             (ABILITIES_COUNT_CUSTOM + 178)
#define ABILITY_DRAGONIZE                   (ABILITIES_COUNT_CUSTOM + 179)
#define ABILITY_BATESIAN_MIMICRY            (ABILITIES_COUNT_CUSTOM + 180)
#define ABILITY_CATS_LUCK                   (ABILITIES_COUNT_CUSTOM + 181)
#define ABILITY_BERSERKER_RAGE              (ABILITIES_COUNT_CUSTOM + 182)
#define ABILITY_RAGNAROK                    (ABILITIES_COUNT_CUSTOM + 183)
#define ABILITY_MACHINE_LEARNING            (ABILITIES_COUNT_CUSTOM + 184)
#define ABILITY_SINGER                      (ABILITIES_COUNT_CUSTOM + 185)
#define ABILITY_LIFE_FORCE_STEALER          (ABILITIES_COUNT_CUSTOM + 186)
#define ABILITY_STATS_SNATCHER              (ABILITIES_COUNT_CUSTOM + 187)
#define ABILITY_ANTI_UB                     (ABILITIES_COUNT_CUSTOM + 188)
#define ABILITY_CHIMERIC                    (ABILITIES_COUNT_CUSTOM + 189)
#define ABILITY_HITEN_MITSURUGI             (ABILITIES_COUNT_CUSTOM + 190)
#define ABILITY_RYUTSUISEN                  (ABILITIES_COUNT_CUSTOM + 191)
#define ABILITY_MASTER_OF_MIMICS            (ABILITIES_COUNT_CUSTOM + 192)
#define ABILITY_MYSTICAL_HORN               (ABILITIES_COUNT_CUSTOM + 193)
#define ABILITY_COLD_BLOODED                (ABILITIES_COUNT_CUSTOM + 194)
#define ABILITY_QUICK_CHARGE                (ABILITIES_COUNT_CUSTOM + 195)
#define ABILITY_FOREST_WITCH                (ABILITIES_COUNT_CUSTOM + 196)
#define ABILITY_DESTRUCTION_COCOON          (ABILITIES_COUNT_CUSTOM + 197)
#define ABILITY_APEX_PREDATOR               (ABILITIES_COUNT_CUSTOM + 198)
#define ABILITY_SILK_ARMOR                  (ABILITIES_COUNT_CUSTOM + 199)
#define ABILITY_ETERNAL_LIFE                (ABILITIES_COUNT_CUSTOM + 200)
#define ABILITY_ADAMANTIUM_SKIN             (ABILITIES_COUNT_CUSTOM + 201)
#define ABILITY_DEVOURER                    (ABILITIES_COUNT_CUSTOM + 202)
#define ABILITY_SIGHT_SHARING               (ABILITIES_COUNT_CUSTOM + 203)
#define ABILITY_SPELL_FIST                  (ABILITIES_COUNT_CUSTOM + 204)
#define ABILITY_FRICTION_MANE               (ABILITIES_COUNT_CUSTOM + 205)
#define ABILITY_THUNDERCLOUDS               (ABILITIES_COUNT_CUSTOM + 206)
#define ABILITY_METALMORPH                  (ABILITIES_COUNT_CUSTOM + 207)
#define ABILITY_TAP_DANCER                  (ABILITIES_COUNT_CUSTOM + 208)
#define ABILITY_VOODOO_DOLL                 (ABILITIES_COUNT_CUSTOM + 209)
#define ABILITY_NIGHTFALL_LULLABY           (ABILITIES_COUNT_CUSTOM + 210)
#define ABILITY_LUNAR_VEIL                  (ABILITIES_COUNT_CUSTOM + 211)
#define ABILITY_PSYCHOKINETIC               (ABILITIES_COUNT_CUSTOM + 212)
#define ABILITY_PACK_TACTICS                (ABILITIES_COUNT_CUSTOM + 213)
#define ABILITY_PACK_LEADER                 (ABILITIES_COUNT_CUSTOM + 214)
#define ABILITY_X_RAY_VISION                (ABILITIES_COUNT_CUSTOM + 215)
#define ABILITY_LONELY_WOLF                 (ABILITIES_COUNT_CUSTOM + 216)
#define ABILITY_LUNAR_LUMINANCE             (ABILITIES_COUNT_CUSTOM + 217)
#define ABILITY_STELLAR_LUMINANCE           (ABILITIES_COUNT_CUSTOM + 218)
#define ABILITY_COSMIC_ENERGY               (ABILITIES_COUNT_CUSTOM + 219)
#define ABILITY_HERO_IN_TRAINING            (ABILITIES_COUNT_CUSTOM + 220)
#define ABILITY_GRANITIC_BODY               (ABILITIES_COUNT_CUSTOM + 221)
#define ABILITY_PYROCLASTIC                 (ABILITIES_COUNT_CUSTOM + 222)
#define ABILITY_HOLLOW_SHELL                (ABILITIES_COUNT_CUSTOM + 223)
#define ABILITY_PETRIFYING_GAZE             (ABILITIES_COUNT_CUSTOM + 224)
#define ABILITY_PATRIARCH                   (ABILITIES_COUNT_CUSTOM + 225)
#define ABILITY_MATRIARCH                   (ABILITIES_COUNT_CUSTOM + 226)
#define ABILITY_GEM_HOARDER                 (ABILITIES_COUNT_CUSTOM + 227)
#define ABILITY_CLEANSING_CHIME             (ABILITIES_COUNT_CUSTOM + 228)
#define ABILITY_JAW_TRAP                    (ABILITIES_COUNT_CUSTOM + 229)
#define ABILITY_POLARIZATION                (ABILITIES_COUNT_CUSTOM + 230)
#define ABILITY_WRESTLING_HEEL              (ABILITIES_COUNT_CUSTOM + 231)
#define ABILITY_PROVOKING_FEUDS             (ABILITIES_COUNT_CUSTOM + 232)
#define ABILITY_OUTBREAK                    (ABILITIES_COUNT_CUSTOM + 233)
#define ABILITY_PANDEMIC                    (ABILITIES_COUNT_CUSTOM + 234)
#define ABILITY_GRIMTOOTH                   (ABILITIES_COUNT_CUSTOM + 235)
#define ABILITY_SLOTTED_SHELL               (ABILITIES_COUNT_CUSTOM + 236)
#define ABILITY_TRAUMATIC_FIST              (ABILITIES_COUNT_CUSTOM + 237)
#define ABILITY_GOLDEN_ARMOR                (ABILITIES_COUNT_CUSTOM + 238)
#define ABILITY_ELEMENTIST                  (ABILITIES_COUNT_CUSTOM + 239)
#define ABILITY_GUARDIAN_DEITY              (ABILITIES_COUNT_CUSTOM + 240)
#define ABILITY_EVOBOOST_SYNC               (ABILITIES_COUNT_CUSTOM + 241)
#define ABILITY_DELUGE                      (ABILITIES_COUNT_CUSTOM + 242)
#define ABILITY_WILDFIRE                    (ABILITIES_COUNT_CUSTOM + 243)
#define ABILITY_BIOENGINEERING              (ABILITIES_COUNT_CUSTOM + 244)
#define ABILITY_AURORA_GUARD                (ABILITIES_COUNT_CUSTOM + 245)
#define ABILITY_PLAYFUL_AGGRO               (ABILITIES_COUNT_CUSTOM + 246)
#define ABILITY_FAIRY_TALES                 (ABILITIES_COUNT_CUSTOM + 247)
#define ABILITY_WITS_END                    (ABILITIES_COUNT_CUSTOM + 248)
#define ABILITY_MONSTROSITY_FUSION          (ABILITIES_COUNT_CUSTOM + 249)
#define ABILITY_LORD_SITH                   (ABILITIES_COUNT_CUSTOM + 250)
#define ABILITY_LIGHTSABER                  (ABILITIES_COUNT_CUSTOM + 251)
#define ABILITY_SHADOW_AURA                 (ABILITIES_COUNT_CUSTOM + 252)
#define ABILITY_GALE_OF_DARKNESS            (ABILITIES_COUNT_CUSTOM + 253)
#define ABILITY_DEFENSIVE_MANEUVER          (ABILITIES_COUNT_CUSTOM + 254)
#define ABILITY_SAVAGE_ATTACKER             (ABILITIES_COUNT_CUSTOM + 255)
#define ABILITY_HEAVILY_ARMOURED            (ABILITIES_COUNT_CUSTOM + 256)
#define ABILITY_EXOSKELETON                 (ABILITIES_COUNT_CUSTOM + 257)
#define ABILITY_CRUSTACEAN                  (ABILITIES_COUNT_CUSTOM + 258)
#define ABILITY_PHOTOVOLTAIC_FRILL          (ABILITIES_COUNT_CUSTOM + 259)
#define ABILITY_PLACEHOLDER_15              (ABILITIES_COUNT_CUSTOM + 260)
#define ABILITY_FACE_SMUSHER                (ABILITIES_COUNT_CUSTOM + 261)
#define ABILITY_METAMORPHOSIS               (ABILITIES_COUNT_CUSTOM + 262)
#define ABILITY_OLD_SCHOOL                  (ABILITIES_COUNT_CUSTOM + 263)
#define ABILITY_MORE_POISON                 (ABILITIES_COUNT_CUSTOM + 264)
#define ABILITY_TIDE_WAITER                 (ABILITIES_COUNT_CUSTOM + 265)
#define ABILITY_VIBRATING_LUMBS             (ABILITIES_COUNT_CUSTOM + 266)
#define ABILITY_MUD_SHIELD                  (ABILITIES_COUNT_CUSTOM + 267)
#define ABILITY_OVERDOSE                    (ABILITIES_COUNT_CUSTOM + 268)
#define ABILITY_DARK_SIDE                   (ABILITIES_COUNT_CUSTOM + 269)
#define ABILITY_ABSORB_ELEMENTS             (ABILITIES_COUNT_CUSTOM + 270)
#define ABILITY_DEEP_SEA_STAR               (ABILITIES_COUNT_CUSTOM + 271)
#define ABILITY_ARCTIC_FORCE                (ABILITIES_COUNT_CUSTOM + 272)
#define ABILITY_TENACITY                    (ABILITIES_COUNT_CUSTOM + 273)
#define ABILITY_FLOWER_GARDENER             (ABILITIES_COUNT_CUSTOM + 274)
#define ABILITY_FLASHING_FINS               (ABILITIES_COUNT_CUSTOM + 275)
#define ABILITY_DANCING_TENTACLES           (ABILITIES_COUNT_CUSTOM + 276)
#define ABILITY_CHAMPION_BELT               (ABILITIES_COUNT_CUSTOM + 277)
#define ABILITY_BONFIRE_BLOSSOM             (ABILITIES_COUNT_CUSTOM + 278)
#define ABILITY_BLACK_MAGICIAN              (ABILITIES_COUNT_CUSTOM + 279)
#define ABILITY_RESONANT_VOICE              (ABILITIES_COUNT_CUSTOM + 280)
#define ABILITY_CONNECTED_BRAINS            (ABILITIES_COUNT_CUSTOM + 281)
#define ABILITY_IRON_EATER                  (ABILITIES_COUNT_CUSTOM + 282)
#define ABILITY_ARMOR_CRACKER               (ABILITIES_COUNT_CUSTOM + 283)
#define ABILITY_DWARVEN_RESILIENCE          (ABILITIES_COUNT_CUSTOM + 284)
#define ABILITY_RED_HOT_CHILI_PEPPERS       (ABILITIES_COUNT_CUSTOM + 285)
#define ABILITY_TACTICAL_RETREAT            (ABILITIES_COUNT_CUSTOM + 286)
#define ABILITY_NEUTRINO_EXHAUST            (ABILITIES_COUNT_CUSTOM + 287)
#define ABILITY_HEAT_CARBURETTOR            (ABILITIES_COUNT_CUSTOM + 288)
#define ABILITY_KAMEN_RIDER                 (ABILITIES_COUNT_CUSTOM + 289)
#define ABILITY_ULTIMATE_SHOWDOWN           (ABILITIES_COUNT_CUSTOM + 290)
#define ABILITY_BATTLE_NETWORK              (ABILITIES_COUNT_CUSTOM + 291)
#define ABILITY_NOISE_CHANGE                (ABILITIES_COUNT_CUSTOM + 292)
#define ABILITY_CALL_REINFORCEMENT          (ABILITIES_COUNT_CUSTOM + 293)
#define ABILITY_SOLO_LEVELING               (ABILITIES_COUNT_CUSTOM + 294)
#define ABILITY_ENVIRONMENT_CLOAK           (ABILITIES_COUNT_CUSTOM + 295)
#define ABILITY_FAERIE_COMPANION            (ABILITIES_COUNT_CUSTOM + 296)
#define ABILITY_STEALTH                     (ABILITIES_COUNT_CUSTOM + 297)
#define ABILITY_STALK                       (ABILITIES_COUNT_CUSTOM + 298)
#define ABILITY_BRANCH_SWING                (ABILITIES_COUNT_CUSTOM + 299)
#define ABILITY_SCENT_MARK                  (ABILITIES_COUNT_CUSTOM + 300)
#define ABILITY_HIGH_TIDE                   (ABILITIES_COUNT_CUSTOM + 301)
#define ABILITY_TOGETHER_WE_STAND           (ABILITIES_COUNT_CUSTOM + 302)
#define ABILITY_PLAGUE_SPREADING            (ABILITIES_COUNT_CUSTOM + 303)
#define ABILITY_STOCKING_PREY               (ABILITIES_COUNT_CUSTOM + 304)
#define ABILITY_DRAGON_HOARD                (ABILITIES_COUNT_CUSTOM + 305)
#define ABILITY_BUG_CATCHER                 (ABILITIES_COUNT_CUSTOM + 306)
#define ABILITY_NEUROTOXIC_VENOM            (ABILITIES_COUNT_CUSTOM + 307)
#define ABILITY_HEMOTOXIC_VENOM             (ABILITIES_COUNT_CUSTOM + 308)
#define ABILITY_SOLENOGLYPHS_2              (ABILITIES_COUNT_CUSTOM + 309)
#define ABILITY_PROSPECTING                 (ABILITIES_COUNT_CUSTOM + 310)
#define ABILITY_OCCULTISM                   (ABILITIES_COUNT_CUSTOM + 311)
#define ABILITY_SPELLWEAVER                 (ABILITIES_COUNT_CUSTOM + 312)
#define ABILITY_TURN_TO_OIL                 (ABILITIES_COUNT_CUSTOM + 313)
#define ABILITY_COLLOSUS                    (ABILITIES_COUNT_CUSTOM + 314)
#define ABILITY_CONTAMINATE                 (ABILITIES_COUNT_CUSTOM + 315)
#define ABILITY_SAWTOOTH_RUSH               (ABILITIES_COUNT_CUSTOM + 316)
#define ABILITY_NOXIOUS_FUMES               (ABILITIES_COUNT_CUSTOM + 317)
#define ABILITY_VOLATILE_FUMES              (ABILITIES_COUNT_CUSTOM + 318)
#define ABILITY_UMBRAL_DOMINION             (ABILITIES_COUNT_CUSTOM + 319)
#define ABILITY_CHRYSALIS_VEIL              (ABILITIES_COUNT_CUSTOM + 320)
#define ABILITY_POLLINATION_SURGE           (ABILITIES_COUNT_CUSTOM + 321)
#define ABILITY_CHILI_FEVER                 (ABILITIES_COUNT_CUSTOM + 322)
#define ABILITY_REMODELING_FRAME            (ABILITIES_COUNT_CUSTOM + 323)
#define ABILITY_NURSERY                     (ABILITIES_COUNT_CUSTOM + 324)
#define ABILITY_AFTERIMAGE                  (ABILITIES_COUNT_CUSTOM + 325)
#define ABILITY_AERO_VOICE                  (ABILITIES_COUNT_CUSTOM + 326)
#define ABILITY_GRAVEKEEPER                 (ABILITIES_COUNT_CUSTOM + 327)
#define ABILITY_SALT_RITUAL                 (ABILITIES_COUNT_CUSTOM + 328)
#define ABILITY_VELOCITY_SHIFT              (ABILITIES_COUNT_CUSTOM + 329)
#define ABILITY_FAE_BANE                    (ABILITIES_COUNT_CUSTOM + 330)
#define ABILITY_BOMBARDMENT                 (ABILITIES_COUNT_CUSTOM + 331)
#define ABILITY_HELLISH_RESISTANCE          (ABILITIES_COUNT_CUSTOM + 332)
#define ABILITY_FAE_TOUCHED                 (ABILITIES_COUNT_CUSTOM + 333)
#define ABILITY_LAST_RITES                  (ABILITIES_COUNT_CUSTOM + 334)
#define ABILITY_LATENT_PSYCHE               (ABILITIES_COUNT_CUSTOM + 335)
#define ABILITY_PSIONIC_DOMINANCE           (ABILITIES_COUNT_CUSTOM + 336)
#define ABILITY_PSIONIC_BACKLASH            (ABILITIES_COUNT_CUSTOM + 337)
#define ABILITY_MIND_FRACTURE               (ABILITIES_COUNT_CUSTOM + 338)
#define ABILITY_GORE_RUSH                   (ABILITIES_COUNT_CUSTOM + 339)
#define ABILITY_UNERRING_IMPALE             (ABILITIES_COUNT_CUSTOM + 340)
#define ABILITY_PERILOUS_STAKE              (ABILITIES_COUNT_CUSTOM + 341)
#define ABILITY_SKY_SOVEREIGN               (ABILITIES_COUNT_CUSTOM + 342)
#define ABILITY_NECROTOXIC_VENOM            (ABILITIES_COUNT_CUSTOM + 343)
#define ABILITY_STONE_SCATTER               (ABILITIES_COUNT_CUSTOM + 344)
#define ABILITY_PLACEHOLDER_13              (ABILITIES_COUNT_CUSTOM + 345)
#define ABILITY_FREECAST                    (ABILITIES_COUNT_CUSTOM + 346)
#define ABILITY_PLACEHOLDER_11              (ABILITIES_COUNT_CUSTOM + 347)
#define ABILITY_SKULLBREAKER                (ABILITIES_COUNT_CUSTOM + 348)
#define ABILITY_VENOM_OVERDRIVE             (ABILITIES_COUNT_CUSTOM + 349)
#define ABILITY_DUNE_TRAP                   (ABILITIES_COUNT_CUSTOM + 350)
#define ABILITY_SAND_GLIDER                 (ABILITIES_COUNT_CUSTOM + 351)
#define ABILITY_PLACEHOLDER_14              (ABILITIES_COUNT_CUSTOM + 352)
#define ABILITY_DISGUSTING_POLLEN           (ABILITIES_COUNT_CUSTOM + 353)
#define ABILITY_DIAMOND_REFLECT             (ABILITIES_COUNT_CUSTOM + 354)
#define ABILITY_CHAIN_REACTION              (ABILITIES_COUNT_CUSTOM + 355)
#define ABILITY_POWER_KEG                   (ABILITIES_COUNT_CUSTOM + 356)
#define ABILITY_SULFUR_FEED                 (ABILITIES_COUNT_CUSTOM + 357)
#define ABILITY_SMOKE_SIGNAL                (ABILITIES_COUNT_CUSTOM + 358)
#define ABILITY_SOOT_VEIL                   (ABILITIES_COUNT_CUSTOM + 359)
#define ABILITY_REACTIVE_ARMOR              (ABILITIES_COUNT_CUSTOM + 360)
#define ABILITY_SIEGE_PAYLOAD               (ABILITIES_COUNT_CUSTOM + 361)
#define ABILITY_LIVING_MONOLITH             (ABILITIES_COUNT_CUSTOM + 362)
#define ABILITY_POWER_OBELISK               (ABILITIES_COUNT_CUSTOM + 363)
#define ABILITY_STONE_SENTINEL              (ABILITIES_COUNT_CUSTOM + 364)
#define ABILITY_RUNIC_STONE                 (ABILITIES_COUNT_CUSTOM + 365)
#define ABILITY_LOVELY_FRAGRANCE            (ABILITIES_COUNT_CUSTOM + 366)
#define ABILITY_OVERCLOCK                   (ABILITIES_COUNT_CUSTOM + 367)
#define ABILITY_FLAVOR_ADAPTATION           (ABILITIES_COUNT_CUSTOM + 368)
#define ABILITY_AWAKENED_MIND               (ABILITIES_COUNT_CUSTOM + 369)
#define ABILITY_SILENT_FLIGHT               (ABILITIES_COUNT_CUSTOM + 370)
#define ABILITY_TEMPEST_WAKE                (ABILITIES_COUNT_CUSTOM + 371)
#define ABILITY_LEECH_SPORE                 (ABILITIES_COUNT_CUSTOM + 372)
#define ABILITY_MAGMA_CHAMBER               (ABILITIES_COUNT_CUSTOM + 373)
#define ABILITY_ABYSSAL_WELLSPRING          (ABILITIES_COUNT_CUSTOM + 374)
#define ABILITY_FEEDING_FRENZY              (ABILITIES_COUNT_CUSTOM + 375)
#define ABILITY_DREADFUL_SMELL              (ABILITIES_COUNT_CUSTOM + 376)
#define ABILITY_IRON_CHIME                  (ABILITIES_COUNT_CUSTOM + 377)
#define ABILITY_IMPROVISED_WEAPON_GRASS     (ABILITIES_COUNT_CUSTOM + 378)
#define ABILITY_IMPROVISED_WEAPON_STEEL     (ABILITIES_COUNT_CUSTOM + 379)
#define ABILITY_IMPROVISED_WEAPON_ROCK      (ABILITIES_COUNT_CUSTOM + 380)
#define ABILITY_BONE_CAGE                   (ABILITIES_COUNT_CUSTOM + 381)
#define ABILITY_SOVEREIGN_CREST             (ABILITIES_COUNT_CUSTOM + 382)
#define ABILITY_OILY_CARAPACE               (ABILITIES_COUNT_CUSTOM + 383)
#define ABILITY_POWER_OVERFLOW              (ABILITIES_COUNT_CUSTOM + 384)
#define ABILITY_STORM_WINGS                 (ABILITIES_COUNT_CUSTOM + 385)
#define ABILITY_SKITTERIZE                  (ABILITIES_COUNT_CUSTOM + 386)
#define ABILITY_ADRENALINE_SURGE            (ABILITIES_COUNT_CUSTOM + 387)
#define ABILITY_PHANTOM_STAR_FIST           (ABILITIES_COUNT_CUSTOM + 388)
#define ABILITY_SUNFORGED_GOLD              (ABILITIES_COUNT_CUSTOM + 389)
#define ABILITY_SILVER_ARMOR                (ABILITIES_COUNT_CUSTOM + 390)
#define ABILITY_POLAR_GUARD                 (ABILITIES_COUNT_CUSTOM + 391)
#define ABILITY_TESLA_COIL                  (ABILITIES_COUNT_CUSTOM + 392)
#define ABILITY_FLUX_BREAK                  (ABILITIES_COUNT_CUSTOM + 393)
#define ABILITY_COLOSSEUM_SURGE             (ABILITIES_COUNT_CUSTOM + 394)
#define ABILITY_DRACONIC_SURGE              (ABILITIES_COUNT_CUSTOM + 395)
#define ABILITY_EVERBURN_SPEAR              (ABILITIES_COUNT_CUSTOM + 396)
#define ABILITY_HYDRENCHYMA                 (ABILITIES_COUNT_CUSTOM + 397)
#define ABILITY_NIGHT_SYNTHESIS             (ABILITIES_COUNT_CUSTOM + 398)
#define ABILITY_WAXY_GUARD                  (ABILITIES_COUNT_CUSTOM + 399)
#define ABILITY_NEEDLE_SKIN                 (ABILITIES_COUNT_CUSTOM + 400)
#define ABILITY_MASTER_PUGILIST             (ABILITIES_COUNT_CUSTOM + 401)
#define ABILITY_THE_WAY_OF_THE_KICK         (ABILITIES_COUNT_CUSTOM + 402)
#define ABILITY_MARTIAL_PRODIGY             (ABILITIES_COUNT_CUSTOM + 403)
#define ABILITY_FUTURE_GAZE                 (ABILITIES_COUNT_CUSTOM + 404)
#define ABILITY_STRADIVARIUS                (ABILITIES_COUNT_CUSTOM + 405)
#define ABILITY_PRESSURE_BURST              (ABILITIES_COUNT_CUSTOM + 406)
#define ABILITY_POWER_SPLASHER              (ABILITIES_COUNT_CUSTOM + 407)
#define ABILITY_JUICEMAKER                  (ABILITIES_COUNT_CUSTOM + 408)
#define ABILITY_GLASS_CANNON                (ABILITIES_COUNT_CUSTOM + 409)
#define ABILITY_MASTER_KICKER               (ABILITIES_COUNT_CUSTOM + 410)
#define ABILITY_LIMIT_BREAKER               (ABILITIES_COUNT_CUSTOM + 411)
#define ABILITY_DRUNKEN_FIST                (ABILITIES_COUNT_CUSTOM + 412)
#define ABILITY_SWEET_GAUGE                 (ABILITIES_COUNT_CUSTOM + 413)
#define ABILITY_BOOZE_REMEDY                (ABILITIES_COUNT_CUSTOM + 414)
#define ABILITY_DESERT_FLOWER               (ABILITIES_COUNT_CUSTOM + 415)
#define ABILITY_SCARECROW_VIGIL             (ABILITIES_COUNT_CUSTOM + 416)
#define ABILITY_HEAVY_SLEEPER               (ABILITIES_COUNT_CUSTOM + 417)
#define ABILITY_DEEP_SLUMBER                (ABILITIES_COUNT_CUSTOM + 418)
#define ABILITY_LOG_LAUNCHER                (ABILITIES_COUNT_CUSTOM + 419)
#define ABILITY_LUMBER_PILLOW               (ABILITIES_COUNT_CUSTOM + 420)
#define ABILITY_ALL_JUST_A_DREAM            (ABILITIES_COUNT_CUSTOM + 421)
//new
#define ABILITY_TRAINING_GROUND             (ABILITIES_COUNT_CUSTOM + 422)
#define ABILITY_GRAPPLE_GUARD               (ABILITIES_COUNT_CUSTOM + 423)
#define ABILITY_THREADLOCK                  (ABILITIES_COUNT_CUSTOM + 424)
#define ABILITY_TRAP_TERRITORY              (ABILITIES_COUNT_CUSTOM + 425)
#define ABILITY_SILKEN_AMBUSH                (ABILITIES_COUNT_CUSTOM + 426)
#define ABILITY_CHARGED_WEB                 (ABILITIES_COUNT_CUSTOM + 427)
#define ABILITY_ROGUE_TACTICS               (ABILITIES_COUNT_CUSTOM + 428)
#define ABILITY_DIRTY_FIGHTING              (ABILITIES_COUNT_CUSTOM + 429)
#define ABILITY_POISONOUS_NEST              (ABILITIES_COUNT_CUSTOM + 430)
#define ABILITY_SPIDER_QUEEN                (ABILITIES_COUNT_CUSTOM + 431)
#define ABILITY_INFUSED_CORE                (ABILITIES_COUNT_CUSTOM + 432)
#define ABILITY_TUGESTEN_ALLOY              (ABILITIES_COUNT_CUSTOM + 433)
#define ABILITY_WYRM_HIDE                   (ABILITIES_COUNT_CUSTOM + 434)
#define ABILITY_STATIC_SHELL                (ABILITIES_COUNT_CUSTOM + 435)
#define ABILITY_BEDROCK                     (ABILITIES_COUNT_CUSTOM + 436)
#define ABILITY_WHITEOUT                    (ABILITIES_COUNT_CUSTOM + 437)
#define ABILITY_BERSERK_FURY                (ABILITIES_COUNT_CUSTOM + 438)
#define ABILITY_INTOXICATE                  (ABILITIES_COUNT_CUSTOM + 439)
#define ABILITY_THIRD_EYE                   (ABILITIES_COUNT_CUSTOM + 440)
#define ABILITY_PSIONIZE                    (ABILITIES_COUNT_CUSTOM + 441)
#define ABILITY_SCRY                        (ABILITIES_COUNT_CUSTOM + 442)
#define ABILITY_WISH_UPON_A_STAR            (ABILITIES_COUNT_CUSTOM + 443)
#define ABILITY_ORACLES_PROPHECY            (ABILITIES_COUNT_CUSTOM + 444)
#define ABILITY_STARLIGHT_VEIL              (ABILITIES_COUNT_CUSTOM + 445)
#define ABILITY_MILLENIUM_COMET             (ABILITIES_COUNT_CUSTOM + 446)
#define ABILITY_SIXTH_SENSE                 (ABILITIES_COUNT_CUSTOM + 447)
#define ABILITY_HEALING_FACTOR              (ABILITIES_COUNT_CUSTOM + 448)
#define ABILITY_WATERLOGGING                (ABILITIES_COUNT_CUSTOM + 449)
#define ABILITY_BATTLE_AURA                 (ABILITIES_COUNT_CUSTOM + 450)
#define ABILITY_TERRAFORM                   (ABILITIES_COUNT_CUSTOM + 451)
#define ABILITY_FIRST_STRIKE                (ABILITIES_COUNT_CUSTOM + 452)
#define ABILITY_DOUBLE_STRIKE               (ABILITIES_COUNT_CUSTOM + 453)
#define ABILITY_HASTE                       (ABILITIES_COUNT_CUSTOM + 454)
#define ABILITY_LIFELINK                    (ABILITIES_COUNT_CUSTOM + 455)
#define ABILITY_REACH                       (ABILITIES_COUNT_CUSTOM + 456)
#define ABILITY_TRAMPLE                     (ABILITIES_COUNT_CUSTOM + 457)
#define ABILITY_DEATHTOUCH                  (ABILITIES_COUNT_CUSTOM + 458)
#define ABILITY_CRYOSTASIS                  (ABILITIES_COUNT_CUSTOM + 459)
#define ABILITY_GENERALIST                  (ABILITIES_COUNT_CUSTOM + 460)
#define ABILITY_HEXPROOF                    (ABILITIES_COUNT_CUSTOM + 461)
#define ABILITY_HERD_LEADER                 (ABILITIES_COUNT_CUSTOM + 462)
#define ABILITY_MENACE                      (ABILITIES_COUNT_CUSTOM + 463)
#define ABILITY_PLANESWALKER                (ABILITIES_COUNT_CUSTOM + 464)
#define ABILITY_VIGILANCE                   (ABILITIES_COUNT_CUSTOM + 465)
#define ABILITY_HYPNOTIC_GAZE               (ABILITIES_COUNT_CUSTOM + 466)
#define ABILITY_INDOMITABLE                 (ABILITIES_COUNT_CUSTOM + 467)
#define ABILITY_NIGHTSTALKER                (ABILITIES_COUNT_CUSTOM + 468)
#define ABILITY_VENGEFUL_SPIRIT             (ABILITIES_COUNT_CUSTOM + 469)
#define ABILITY_SPIRITUAL_OFFERINGS         (ABILITIES_COUNT_CUSTOM + 470)
#define ABILITY_CHARGE_UP                   (ABILITIES_COUNT_CUSTOM + 471)
#define ABILITY_BATTLE_TRANCE               (ABILITIES_COUNT_CUSTOM + 472)
#define ABILITY_LOVE_SERENADE               (ABILITIES_COUNT_CUSTOM + 473)
#define ABILITY_LOST_TECHNOLOGY             (ABILITIES_COUNT_CUSTOM + 474)
#define ABILITY_CLAY_VESSEL                 (ABILITIES_COUNT_CUSTOM + 475)
#define ABILITY_ANIMATED_CONSTRUCT          (ABILITIES_COUNT_CUSTOM + 476)
#define ABILITY_OCEANS_COVENANT             (ABILITIES_COUNT_CUSTOM + 477)
#define ABILITY_DARK_BRIBE                  (ABILITIES_COUNT_CUSTOM + 478)
#define ABILITY_REVENANT_CORAL              (ABILITIES_COUNT_CUSTOM + 479)
#define ABILITY_CORAL_BLEACHING             (ABILITIES_COUNT_CUSTOM + 480)
#define ABILITY_ZOOXANTHELLAE               (ABILITIES_COUNT_CUSTOM + 481)
#define ABILITY_DINOFLAGELLATE              (ABILITIES_COUNT_CUSTOM + 482)
#define ABILITY_ALGAL_SHIELD                (ABILITIES_COUNT_CUSTOM + 483)
#define ABILITY_BARRIER_REEF                (ABILITIES_COUNT_CUSTOM + 484)
#define ABILITY_PLACEHOLDER_12              (ABILITIES_COUNT_CUSTOM + 485)
#define ABILITY_MUTUALISM                   (ABILITIES_COUNT_CUSTOM + 486)
#define ABILITY_UNTAPPED_POTENCIAL          (ABILITIES_COUNT_CUSTOM + 487)
#define ABILITY_LITTLE_CHAMPION             (ABILITIES_COUNT_CUSTOM + 488)
#define ABILITY_UNSTABLE_CORE               (ABILITIES_COUNT_CUSTOM + 489)
#define ABILITY_BERRY_BULK                  (ABILITIES_COUNT_CUSTOM + 490)
#define ABILITY_DEBILITATE                  (ABILITIES_COUNT_CUSTOM + 491)
#define ABILITY_POLAR_CURRENT               (ABILITIES_COUNT_CUSTOM + 492)
#define ABILITY_KILLER_WHALE                (ABILITIES_COUNT_CUSTOM + 493)
#define ABILITY_ECHOLOCATION                (ABILITIES_COUNT_CUSTOM + 494)
#define ABILITY_FIREBRAND                   (ABILITIES_COUNT_CUSTOM + 495)
#define ABILITY_MASTER_FENCER               (ABILITIES_COUNT_CUSTOM + 496)
#define ABILITY_EN_GARDE                    (ABILITIES_COUNT_CUSTOM + 497)
#define ABILITY_RUTHLESS_PREDATOR           (ABILITIES_COUNT_CUSTOM + 498)
#define ABILITY_REIGN_OF_ANGER              (ABILITIES_COUNT_CUSTOM + 499)
#define ABILITY_REINDEER_RIDER              (ABILITIES_COUNT_CUSTOM + 500)
#define ABILITY_DEFLECTOR_HULL              (ABILITIES_COUNT_CUSTOM + 501)
#define ABILITY_LURKING_MENACE              (ABILITIES_COUNT_CUSTOM + 502)
#define ABILITY_LOST_KNOWLEDGE              (ABILITIES_COUNT_CUSTOM + 503)
#define ABILITY_CLEAR_MINDED                (ABILITIES_COUNT_CUSTOM + 504)
#define ABILITY_MADNESS_MIND                (ABILITIES_COUNT_CUSTOM + 505)
#define ABILITY_SUBJUGATE                   (ABILITIES_COUNT_CUSTOM + 506)
#define ABILITY_GENETIC_MODIFIED_S          (ABILITIES_COUNT_CUSTOM + 507)
#define ABILITY_GENETIC_MODIFIED_A          (ABILITIES_COUNT_CUSTOM + 508)
#define ABILITY_GENETIC_MODIFIED_B          (ABILITIES_COUNT_CUSTOM + 509)
#define ABILITY_GENETIC_MODIFIED_C          (ABILITIES_COUNT_CUSTOM + 510)
#define ABILITY_GENETIC_MODIFIED_D          (ABILITIES_COUNT_CUSTOM + 511)
#define ABILITY_HOMUNCULUS                  (ABILITIES_COUNT_CUSTOM + 512)
#define ABILITY_HAWK_EYE                    (ABILITIES_COUNT_CUSTOM + 513)
#define ABILITY_VULTURE_EYE                 (ABILITIES_COUNT_CUSTOM + 514)
#define ABILITY_FALCON_EYE                  (ABILITIES_COUNT_CUSTOM + 515)
#define ABILITY_OWL_EYE                     (ABILITIES_COUNT_CUSTOM + 516)
#define ABILITY_EAGLE_EYE                   (ABILITIES_COUNT_CUSTOM + 517)
#define ABILITY_BUG_COLONY                  (ABILITIES_COUNT_CUSTOM + 518)
#define ABILITY_WARDING_BELLS               (ABILITIES_COUNT_CUSTOM + 519)
#define ABILITY_BEE_QUEEN                   (ABILITIES_COUNT_CUSTOM + 520)
#define ABILITY_MASTERMIND                  (ABILITIES_COUNT_CUSTOM + 521)
#define ABILITY_MESMERIZE                   (ABILITIES_COUNT_CUSTOM + 522)
#define ABILITY_WAR_DRUMS                   (ABILITIES_COUNT_CUSTOM + 523)
#define ABILITY_TOXIC_DUST                  (ABILITIES_COUNT_CUSTOM + 524)
#define ABILITY_BUBBLE_MASK                 (ABILITIES_COUNT_CUSTOM + 525)
#define ABILITY_TIME_SKIP                   (ABILITIES_COUNT_CUSTOM + 526)
#define ABILITY_VIRAL_BOOST                 (ABILITIES_COUNT_CUSTOM + 527)
#define ABILITY_FERTILIZER                  (ABILITIES_COUNT_CUSTOM + 528)
#define ABILITY_MEGAMORPHOSIS               (ABILITIES_COUNT_CUSTOM + 529)
#define ABILITY_ARCHMORPHOSIS               (ABILITIES_COUNT_CUSTOM + 530)
#define ABILITY_PROBOSCIS                   (ABILITIES_COUNT_CUSTOM + 531)
#define ABILITY_MYCELIAL_NETWORK            (ABILITIES_COUNT_CUSTOM + 532)
#define ABILITY_FLORESSENCE                 (ABILITIES_COUNT_CUSTOM + 533)
#define ABILITY_POSEIDON_GUARD              (ABILITIES_COUNT_CUSTOM + 534)
#define ABILITY_VERDANT_OVERGROW            (ABILITIES_COUNT_CUSTOM + 535)
#define ABILITY_INFERNO_BLAZE               (ABILITIES_COUNT_CUSTOM + 536)
#define ABILITY_RAGING_TORRENT              (ABILITIES_COUNT_CUSTOM + 537)
#define ABILITY_FISH_HARPOON                (ABILITIES_COUNT_CUSTOM + 538)
#define ABILITY_GOREMASTER                  (ABILITIES_COUNT_CUSTOM + 539)
#define ABILITY_WILD_STALLION               (ABILITIES_COUNT_CUSTOM + 540)
#define ABILITY_GALLOP_HERD                 (ABILITIES_COUNT_CUSTOM + 541)
#define ABILITY_GILL_FILTER                 (ABILITIES_COUNT_CUSTOM + 542)
#define ABILITY_BRANCHIAL_SHIELD            (ABILITIES_COUNT_CUSTOM + 543)
#define ABILITY_RELENTLESS_FIST             (ABILITIES_COUNT_CUSTOM + 544)
#define ABILITY_BRAWLER_FIST                (ABILITIES_COUNT_CUSTOM + 545)
#define ABILITY_GENTLE_FIST                  (ABILITIES_COUNT_CUSTOM + 546)
#define ABILITY_COMBO_FIST                  (ABILITIES_COUNT_CUSTOM + 547)
#define ABILITY_PHYTOPARASITE               (ABILITIES_COUNT_CUSTOM + 548)
#define ABILITY_DANDELION_DRIFT             (ABILITIES_COUNT_CUSTOM + 549)
#define ABILITY_COTTON_CUSHION              (ABILITIES_COUNT_CUSTOM + 550)
#define ABILITY_SEED_SCATTER                (ABILITIES_COUNT_CUSTOM + 551)
#define ABILITY_CRAZY_VINES                 (ABILITIES_COUNT_CUSTOM + 552)
#define ABILITY_YOKAI                       (ABILITIES_COUNT_CUSTOM + 553)
#define ABILITY_ONI                         (ABILITIES_COUNT_CUSTOM + 554)
#define ABILITY_MONKEY_KING                 (ABILITIES_COUNT_CUSTOM + 555)
#define ABILITY_PRIMATE_TROOP               (ABILITIES_COUNT_CUSTOM + 556)
#define ABILITY_STRING_VEIL                 (ABILITIES_COUNT_CUSTOM + 557)
#define ABILITY_ULTRA_SPACIAN               (ABILITIES_COUNT_CUSTOM + 558)
#define ABILITY_ROCKET_BOOSTERS             (ABILITIES_COUNT_CUSTOM + 559)
#define ABILITY_POWDER_DUST                 (ABILITIES_COUNT_CUSTOM + 560)
#define ABILITY_ICEBREAKER                  (ABILITIES_COUNT_CUSTOM + 561)
#define ABILITY_DRAGONBORN                  (ABILITIES_COUNT_CUSTOM + 562)
#define ABILITY_EARTHWORM                   (ABILITIES_COUNT_CUSTOM + 563)
#define ABILITY_WEAPON_BOND                 (ABILITIES_COUNT_CUSTOM + 564)
#define ABILITY_ELDRITCH_STRIKE             (ABILITIES_COUNT_CUSTOM + 565)
#define ABILITY_SHARED_BULWARK              (ABILITIES_COUNT_CUSTOM + 566)
#define ABILITY_RADIANT_CRYSTAL             (ABILITIES_COUNT_CUSTOM + 567)
#define ABILITY_PRISMATIC_CORE              (ABILITIES_COUNT_CUSTOM + 568)
#define ABILITY_RENEWING_SPINES             (ABILITIES_COUNT_CUSTOM + 569)
#define ABILITY_ADAMANTINE_CLAWS            (ABILITIES_COUNT_CUSTOM + 570)
#define ABILITY_CRITICAL_MASS               (ABILITIES_COUNT_CUSTOM + 571)
#define ABILITY_PERFECT_MIMIC               (ABILITIES_COUNT_CUSTOM + 572)
#define ABILITY_COAL_IGNITION               (ABILITIES_COUNT_CUSTOM + 573)
#define ABILITY_WAR_PRIEST                  (ABILITIES_COUNT_CUSTOM + 574)
#define ABILITY_SNAKE_EYE                   (ABILITIES_COUNT_CUSTOM + 575)
#define ABILITY_PHOTOSYNTHESIS              (ABILITIES_COUNT_CUSTOM + 576)
#define ABILITY_MASTER_CHEF                 (ABILITIES_COUNT_CUSTOM + 577)
#define ABILITY_OMELETE_MAKER               (ABILITIES_COUNT_CUSTOM + 578)
#define ABILITY_CROWDED_NEST                (ABILITIES_COUNT_CUSTOM + 579)
#define ABILITY_PLAY_DEAD                   (ABILITIES_COUNT_CUSTOM + 580)
#define ABILITY_SLOW_METABOLISM             (ABILITIES_COUNT_CUSTOM + 581)
#define ABILITY_THICK_SKIN                  (ABILITIES_COUNT_CUSTOM + 582)
#define ABILITY_PARROT_MIMICRY              (ABILITIES_COUNT_CUSTOM + 583)
#define ABILITY_TRANSMUTATION               (ABILITIES_COUNT_CUSTOM + 584)
#define ABILITY_FLEET_FOOTWORK              (ABILITIES_COUNT_CUSTOM + 585)
#define ABILITY_STORMS_FAVOR                (ABILITIES_COUNT_CUSTOM + 586)
#define ABILITY_GOOD_LUCK                   (ABILITIES_COUNT_CUSTOM + 587)
#define ABILITY_RELIABILITY                 (ABILITIES_COUNT_CUSTOM + 588)
#define ABILITY_TRUSTWORTHY                 (ABILITIES_COUNT_CUSTOM + 589)
#define ABILITY_FAST_LEARNING               (ABILITIES_COUNT_CUSTOM + 590)
#define ABILITY_FROSTBORN                   (ABILITIES_COUNT_CUSTOM + 591)
#define ABILITY_BREAKTHROUGH                (ABILITIES_COUNT_CUSTOM + 592)
#define ABILITY_LOST_EMOTIONS               (ABILITIES_COUNT_CUSTOM + 593)
#define ABILITY_LOST_WILLPOWER              (ABILITIES_COUNT_CUSTOM + 594)
#define ABILITY_RIFTWALK                  (ABILITIES_COUNT_CUSTOM + 595)
#define ABILITY_SPACETIME_STRAIN            (ABILITIES_COUNT_CUSTOM + 596)
#define ABILITY_ANTIMATTER_VEIL             (ABILITIES_COUNT_CUSTOM + 597)
#define ABILITY_TUNNEL_RUNNER               (ABILITIES_COUNT_CUSTOM + 598)
#define ABILITY_HYPERACTIVE                 (ABILITIES_COUNT_CUSTOM + 599)
#define ABILITY_SKY_DIVER                   (ABILITIES_COUNT_CUSTOM + 600)
#define ABILITY_CANNON_MODE                 (ABILITIES_COUNT_CUSTOM + 601)
#define ABILITY_JET_MODE                    (ABILITIES_COUNT_CUSTOM + 602)
#define ABILITY_HOARFROST_SKIN              (ABILITIES_COUNT_CUSTOM + 603)
#define ABILITY_ASTEROID_BELT               (ABILITIES_COUNT_CUSTOM + 604)
#define ABILITY_REFLECT_DAMAGE              (ABILITIES_COUNT_CUSTOM + 605)
#define ABILITY_JACK_FROST                  (ABILITIES_COUNT_CUSTOM + 606)
#define ABILITY_DUNEWARD                    (ABILITIES_COUNT_CUSTOM + 607)
#define ABILITY_TURBULENCE                  (ABILITIES_COUNT_CUSTOM + 608)
#define ABILITY_VAMPIRE_ASCENDANT           (ABILITIES_COUNT_CUSTOM + 609)
#define ABILITY_WATCHFUL_EYEBALL            (ABILITIES_COUNT_CUSTOM + 610)
#define ABILITY_IRON_WILL                   (ABILITIES_COUNT_CUSTOM + 611)
#define ABILITY_OILY_LOCKS                  (ABILITIES_COUNT_CUSTOM + 612)
#define ABILITY_CURLY_HAIR                  (ABILITIES_COUNT_CUSTOM + 613)
#define ABILITY_MEGA_MANE                   (ABILITIES_COUNT_CUSTOM + 614)
#define ABILITY_MOCOUS_COAT                 (ABILITIES_COUNT_CUSTOM + 615)
#define ABILITY_HEALING_AROMA               (ABILITIES_COUNT_CUSTOM + 616)
#define ABILITY_MALIGNATE                   (ABILITIES_COUNT_CUSTOM + 617)
#define ABILITY_GRAVITROPISM                (ABILITIES_COUNT_CUSTOM + 618)
#define ABILITY_PHOTOTROPISM                (ABILITIES_COUNT_CUSTOM + 619)
#define ABILITY_LURELIGHT                   (ABILITIES_COUNT_CUSTOM + 620)
#define ABILITY_DEEP_DWELLER                (ABILITIES_COUNT_CUSTOM + 621)
#define ABILITY_BENTHIC_ORGANISM            (ABILITIES_COUNT_CUSTOM + 622)
#define ABILITY_FROM_THE_VOID               (ABILITIES_COUNT_CUSTOM + 623)
#define ABILITY_AURA_GUARD                  (ABILITIES_COUNT_CUSTOM + 624)
#define ABILITY_GRIM_OMEN                   (ABILITIES_COUNT_CUSTOM + 625)
#define ABILITY_CHRONOBREAK                 (ABILITIES_COUNT_CUSTOM + 626)
#define ABILITY_OUTLANDER                   (ABILITIES_COUNT_CUSTOM + 627)
#define ABILITY_MEDICINE_SCALE              (ABILITIES_COUNT_CUSTOM + 628)

#define ABILITIES_COUNT                     (ABILITIES_COUNT_CUSTOM + 629)

#endif  // GUARD_CONSTANTS_ABILITIES_H
