#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

#define ABILITY_NONE 0
#define ABILITY_STENCH 1
#define ABILITY_DRIZZLE 2
#define ABILITY_SPEED_BOOST 3
#define ABILITY_BATTLE_ARMOR 4
#define ABILITY_STURDY 5
#define ABILITY_DAMP 6
#define ABILITY_LIMBER 7
#define ABILITY_SAND_VEIL 8
#define ABILITY_STATIC 9
#define ABILITY_VOLT_ABSORB 10
#define ABILITY_WATER_ABSORB 11
#define ABILITY_OBLIVIOUS 12
#define ABILITY_CLOUD_NINE 13
#define ABILITY_COMPOUND_EYES 14
#define ABILITY_INSOMNIA 15
#define ABILITY_COLOR_CHANGE 16
#define ABILITY_IMMUNITY 17
#define ABILITY_FLASH_FIRE 18
#define ABILITY_SHIELD_DUST 19
#define ABILITY_OWN_TEMPO 20
#define ABILITY_SUCTION_CUPS 21
#define ABILITY_INTIMIDATE 22
#define ABILITY_SHADOW_TAG 23
#define ABILITY_ROUGH_SKIN 24
#define ABILITY_WONDER_GUARD 25
#define ABILITY_LEVITATE 26
#define ABILITY_EFFECT_SPORE 27
#define ABILITY_SYNCHRONIZE 28
#define ABILITY_CLEAR_BODY 29
#define ABILITY_NATURAL_CURE 30
#define ABILITY_LIGHTNING_ROD 31
#define ABILITY_SERENE_GRACE 32
#define ABILITY_SWIFT_SWIM 33
#define ABILITY_CHLOROPHYLL 34
#define ABILITY_ILLUMINATE 35
#define ABILITY_TRACE 36
#define ABILITY_HUGE_POWER 37
#define ABILITY_POISON_POINT 38
#define ABILITY_INNER_FOCUS 39
#define ABILITY_MAGMA_ARMOR 40
#define ABILITY_WATER_VEIL 41
#define ABILITY_MAGNET_PULL 42
#define ABILITY_SOUNDPROOF 43
#define ABILITY_RAIN_DISH 44
#define ABILITY_SAND_STREAM 45
#define ABILITY_PRESSURE 46
#define ABILITY_THICK_FAT 47
#define ABILITY_EARLY_BIRD 48
#define ABILITY_FLAME_BODY 49
#define ABILITY_RUN_AWAY 50
#define ABILITY_KEEN_EYE 51
#define ABILITY_HYPER_CUTTER 52
#define ABILITY_PICKUP 53
#define ABILITY_TRUANT 54
#define ABILITY_HUSTLE 55
#define ABILITY_CUTE_CHARM 56
#define ABILITY_PLUS 57
#define ABILITY_MINUS 58
#define ABILITY_FORECAST 59
#define ABILITY_STICKY_HOLD 60
#define ABILITY_SHED_SKIN 61
#define ABILITY_GUTS 62
#define ABILITY_MARVEL_SCALE 63
#define ABILITY_LIQUID_OOZE 64
#define ABILITY_OVERGROW 65
#define ABILITY_BLAZE 66
#define ABILITY_TORRENT 67
#define ABILITY_SWARM 68
#define ABILITY_ROCK_HEAD 69
#define ABILITY_DROUGHT 70
#define ABILITY_ARENA_TRAP 71
#define ABILITY_VITAL_SPIRIT 72
#define ABILITY_WHITE_SMOKE 73
#define ABILITY_PURE_POWER 74
#define ABILITY_SHELL_ARMOR 75
#define ABILITY_AIR_LOCK 76

#define ABILITIES_COUNT_GEN3 77

// Gen 4
#define ABILITY_TANGLED_FEET 77
#define ABILITY_MOTOR_DRIVE 78
#define ABILITY_RIVALRY 79
#define ABILITY_STEADFAST 80
#define ABILITY_SNOW_CLOAK 81
#define ABILITY_GLUTTONY 82
#define ABILITY_ANGER_POINT 83
#define ABILITY_UNBURDEN 84
#define ABILITY_HEATPROOF 85
#define ABILITY_SIMPLE 86
#define ABILITY_DRY_SKIN 87
#define ABILITY_DOWNLOAD 88
#define ABILITY_IRON_FIST 89
#define ABILITY_POISON_HEAL 90
#define ABILITY_ADAPTABILITY 91
#define ABILITY_SKILL_LINK 92
#define ABILITY_HYDRATION 93
#define ABILITY_SOLAR_POWER 94
#define ABILITY_QUICK_FEET 95
#define ABILITY_NORMALIZE 96
#define ABILITY_SNIPER 97
#define ABILITY_MAGIC_GUARD 98
#define ABILITY_NO_GUARD 99
#define ABILITY_STALL 100
#define ABILITY_TECHNICIAN 101
#define ABILITY_LEAF_GUARD 102
#define ABILITY_KLUTZ 103
#define ABILITY_MOLD_BREAKER 104
#define ABILITY_SUPER_LUCK 105
#define ABILITY_AFTERMATH 106
#define ABILITY_ANTICIPATION 107
#define ABILITY_FOREWARN 108
#define ABILITY_UNAWARE 109
#define ABILITY_TINTED_LENS 110
#define ABILITY_FILTER 111
#define ABILITY_SLOW_START 112
#define ABILITY_SCRAPPY 113
#define ABILITY_STORM_DRAIN 114
#define ABILITY_ICE_BODY 115
#define ABILITY_SOLID_ROCK 116
#define ABILITY_SNOW_WARNING 117
#define ABILITY_HONEY_GATHER 118
#define ABILITY_FRISK 119
#define ABILITY_RECKLESS 120
#define ABILITY_MULTITYPE 121
#define ABILITY_FLOWER_GIFT 122
#define ABILITY_BAD_DREAMS 123

#define ABILITIES_COUNT_GEN4 124

// Gen 5
#define ABILITY_PICKPOCKET 124
#define ABILITY_SHEER_FORCE 125
#define ABILITY_CONTRARY 126
#define ABILITY_UNNERVE 127
#define ABILITY_DEFIANT 128
#define ABILITY_DEFEATIST 129
#define ABILITY_CURSED_BODY 130
#define ABILITY_HEALER 131
#define ABILITY_FRIEND_GUARD 132
#define ABILITY_WEAK_ARMOR 133
#define ABILITY_HEAVY_METAL 134
#define ABILITY_LIGHT_METAL 135
#define ABILITY_MULTISCALE 136
#define ABILITY_TOXIC_BOOST 137
#define ABILITY_FLARE_BOOST 138
#define ABILITY_HARVEST 139
#define ABILITY_TELEPATHY 140
#define ABILITY_MOODY 141
#define ABILITY_OVERCOAT 142
#define ABILITY_POISON_TOUCH 143
#define ABILITY_REGENERATOR 144
#define ABILITY_BIG_PECKS 145
#define ABILITY_SAND_RUSH 146
#define ABILITY_WONDER_SKIN 147
#define ABILITY_ANALYTIC 148
#define ABILITY_ILLUSION 149
#define ABILITY_IMPOSTER 150
#define ABILITY_INFILTRATOR 151
#define ABILITY_MUMMY 152
#define ABILITY_MOXIE 153
#define ABILITY_JUSTIFIED 154
#define ABILITY_RATTLED 155
#define ABILITY_MAGIC_BOUNCE 156
#define ABILITY_SAP_SIPPER 157
#define ABILITY_PRANKSTER 158
#define ABILITY_SAND_FORCE 159
#define ABILITY_IRON_BARBS 160
#define ABILITY_ZEN_MODE 161
#define ABILITY_VICTORY_STAR 162
#define ABILITY_TURBOBLAZE 163
#define ABILITY_TERAVOLT 164

#define ABILITIES_COUNT_GEN5 165

// Gen 6
#define ABILITY_AROMA_VEIL 165
#define ABILITY_FLOWER_VEIL 166
#define ABILITY_CHEEK_POUCH 167
#define ABILITY_PROTEAN 168
#define ABILITY_FUR_COAT 169
#define ABILITY_MAGICIAN 170
#define ABILITY_BULLETPROOF 171
#define ABILITY_COMPETITIVE 172
#define ABILITY_STRONG_JAW 173
#define ABILITY_REFRIGERATE 174
#define ABILITY_SWEET_VEIL 175
#define ABILITY_STANCE_CHANGE 176
#define ABILITY_GALE_WINGS 177
#define ABILITY_MEGA_LAUNCHER 178
#define ABILITY_GRASS_PELT 179
#define ABILITY_SYMBIOSIS 180
#define ABILITY_TOUGH_CLAWS 181
#define ABILITY_PIXILATE 182
#define ABILITY_GOOEY 183
#define ABILITY_AERILATE 184
#define ABILITY_PARENTAL_BOND 185
#define ABILITY_DARK_AURA 186
#define ABILITY_FAIRY_AURA 187
#define ABILITY_AURA_BREAK 188
#define ABILITY_PRIMORDIAL_SEA 189
#define ABILITY_DESOLATE_LAND 190
#define ABILITY_DELTA_STREAM 191

#define ABILITIES_COUNT_GEN6 192

// Gen 7
#define ABILITY_STAMINA 192
#define ABILITY_WIMP_OUT 193
#define ABILITY_EMERGENCY_EXIT 194
#define ABILITY_WATER_COMPACTION 195
#define ABILITY_MERCILESS 196
#define ABILITY_SHIELDS_DOWN 197
#define ABILITY_STAKEOUT 198
#define ABILITY_WATER_BUBBLE 199
#define ABILITY_STEELWORKER 200
#define ABILITY_BERSERK 201
#define ABILITY_SLUSH_RUSH 202
#define ABILITY_LONG_REACH 203
#define ABILITY_LIQUID_VOICE 204
#define ABILITY_TRIAGE 205
#define ABILITY_GALVANIZE 206
#define ABILITY_SURGE_SURFER 207
#define ABILITY_SCHOOLING 208
#define ABILITY_DISGUISE 209
#define ABILITY_BATTLE_BOND 210
#define ABILITY_POWER_CONSTRUCT 211
#define ABILITY_CORROSION 212
#define ABILITY_COMATOSE 213
#define ABILITY_QUEENLY_MAJESTY 214
#define ABILITY_INNARDS_OUT 215
#define ABILITY_DANCER 216
#define ABILITY_BATTERY 217
#define ABILITY_FLUFFY 218
#define ABILITY_DAZZLING 219
#define ABILITY_SOUL_HEART 220
#define ABILITY_TANGLING_HAIR 221
#define ABILITY_RECEIVER 222
#define ABILITY_POWER_OF_ALCHEMY 223
#define ABILITY_BEAST_BOOST 224
#define ABILITY_RKS_SYSTEM 225
#define ABILITY_ELECTRIC_SURGE 226
#define ABILITY_PSYCHIC_SURGE 227
#define ABILITY_MISTY_SURGE 228
#define ABILITY_GRASSY_SURGE 229
#define ABILITY_FULL_METAL_BODY 230
#define ABILITY_SHADOW_SHIELD 231
#define ABILITY_PRISM_ARMOR 232
#define ABILITY_NEUROFORCE 233

#define ABILITIES_COUNT_GEN7 234

// Gen 8
#define ABILITY_INTREPID_SWORD 234
#define ABILITY_DAUNTLESS_SHIELD 235
#define ABILITY_LIBERO 236
#define ABILITY_BALL_FETCH 237
#define ABILITY_COTTON_DOWN 238
#define ABILITY_PROPELLER_TAIL 239
#define ABILITY_MIRROR_ARMOR 240
#define ABILITY_GULP_MISSILE 241
#define ABILITY_STALWART 242
#define ABILITY_STEAM_ENGINE 243
#define ABILITY_PUNK_ROCK 244
#define ABILITY_SAND_SPIT 245
#define ABILITY_ICE_SCALES 246
#define ABILITY_RIPEN 247
#define ABILITY_ICE_FACE 248
#define ABILITY_POWER_SPOT 249
#define ABILITY_MIMICRY 250
#define ABILITY_SCREEN_CLEANER 251
#define ABILITY_STEELY_SPIRIT 252
#define ABILITY_PERISH_BODY 253
#define ABILITY_WANDERING_SPIRIT 254
#define ABILITY_GORILLA_TACTICS 255
#define ABILITY_NEUTRALIZING_GAS 256
#define ABILITY_PASTEL_VEIL 257
#define ABILITY_HUNGER_SWITCH 258
#define ABILITY_QUICK_DRAW 259
#define ABILITY_UNSEEN_FIST 260
#define ABILITY_CURIOUS_MEDICINE 261
#define ABILITY_TRANSISTOR 262
#define ABILITY_DRAGONS_MAW 263
#define ABILITY_CHILLING_NEIGH 264
#define ABILITY_GRIM_NEIGH 265
#define ABILITY_AS_ONE_ICE_RIDER 266
#define ABILITY_AS_ONE_SHADOW_RIDER 267

#define ABILITIES_COUNT_GEN8 268

// Gen 9
#define ABILITY_LINGERING_AROMA 268
#define ABILITY_SEED_SOWER 269
#define ABILITY_THERMAL_EXCHANGE 270
#define ABILITY_ANGER_SHELL 271
#define ABILITY_PURIFYING_SALT 272
#define ABILITY_WELL_BAKED_BODY 273
#define ABILITY_WIND_RIDER 274
#define ABILITY_GUARD_DOG 275
#define ABILITY_ROCKY_PAYLOAD 276
#define ABILITY_WIND_POWER 277
#define ABILITY_ZERO_TO_HERO 278
#define ABILITY_COMMANDER 279
#define ABILITY_ELECTROMORPHOSIS 280
#define ABILITY_PROTOSYNTHESIS 281
#define ABILITY_QUARK_DRIVE 282
#define ABILITY_GOOD_AS_GOLD 283
#define ABILITY_VESSEL_OF_RUIN 284
#define ABILITY_SWORD_OF_RUIN 285
#define ABILITY_TABLETS_OF_RUIN 286
#define ABILITY_BEADS_OF_RUIN 287
#define ABILITY_ORICHALCUM_PULSE 288
#define ABILITY_HADRON_ENGINE 289
#define ABILITY_OPPORTUNIST 290
#define ABILITY_CUD_CHEW 291
#define ABILITY_SHARPNESS 292
#define ABILITY_SUPREME_OVERLORD 293
#define ABILITY_COSTAR 294
#define ABILITY_TOXIC_DEBRIS 295
#define ABILITY_ARMOR_TAIL 296
#define ABILITY_EARTH_EATER 297
#define ABILITY_MYCELIUM_MIGHT 298
#define ABILITY_HOSPITALITY 299
#define ABILITY_MINDS_EYE 300
#define ABILITY_EMBODY_ASPECT_TEAL 301
#define ABILITY_EMBODY_ASPECT_HEARTHFLAME 302
#define ABILITY_EMBODY_ASPECT_WELLSPRING 303
#define ABILITY_EMBODY_ASPECT_CORNERSTONE 304
#define ABILITY_TOXIC_CHAIN 305
#define ABILITY_SUPERSWEET_SYRUP 306

#define ABILITIES_COUNT_GEN9 307

#define ABILITIES_COUNT_CUSTOM              (ABILITIES_COUNT_GEN9)

// Custom Abilities
#define ABILITY_FLOCK                       (ABILITIES_COUNT_CUSTOM + 0)
#define ABILITY_SHORT_CIRCUIT               (ABILITIES_COUNT_CUSTOM + 1)
#define ABILITY_RAMPAGE                     (ABILITIES_COUNT_CUSTOM + 2)
#define ABILITY_LET_IT_RIP                  (ABILITIES_COUNT_CUSTOM + 3)
#define ABILITY_HIGH_VOLTAGE                (ABILITIES_COUNT_CUSTOM + 4)
#define ABILITY_PERMAFROST                  (ABILITIES_COUNT_CUSTOM + 5)
#define ABILITY_PRECISE_FIST                (ABILITIES_COUNT_CUSTOM + 6)
#define ABILITY_HEARTBREAKER                (ABILITIES_COUNT_CUSTOM + 7)
#define ABILITY_HYDRATE                     (ABILITIES_COUNT_CUSTOM + 8)
#define ABILITY_BURNATE                     (ABILITIES_COUNT_CUSTOM + 9)
#define ABILITY_GROUNDATE                   (ABILITIES_COUNT_CUSTOM + 10)
#define ABILITY_ADAPTATION                  (ABILITIES_COUNT_CUSTOM + 11)
#define ABILITY_AIRBOURNE_STYLE             (ABILITIES_COUNT_CUSTOM + 12)
#define ABILITY_AERODYNAMICS                (ABILITIES_COUNT_CUSTOM + 13)
#define ABILITY_ARTILLERY                   (ABILITIES_COUNT_CUSTOM + 14)
#define ABILITY_AVENGER                     (ABILITIES_COUNT_CUSTOM + 15)
#define ABILITY_BAD_LUCK                    (ABILITIES_COUNT_CUSTOM + 16)
#define ABILITY_BEDOUIN                     (ABILITIES_COUNT_CUSTOM + 17)
#define ABILITY_BATTLE_FURY                 (ABILITIES_COUNT_CUSTOM + 18)
#define ABILITY_BURNING_SURGE               (ABILITIES_COUNT_CUSTOM + 19)
#define ABILITY_CARNIVOROUS                 (ABILITIES_COUNT_CUSTOM + 20)
#define ABILITY_BIG_LEAVES                  (ABILITIES_COUNT_CUSTOM + 21)
#define ABILITY_CURSE_SURGE                 (ABILITIES_COUNT_CUSTOM + 22)
#define ABILITY_EXPERTISE                   (ABILITIES_COUNT_CUSTOM + 23)
#define ABILITY_FROSTBITE                   (ABILITIES_COUNT_CUSTOM + 24)
#define ABILITY_FULL_BELLY                  (ABILITIES_COUNT_CUSTOM + 25)
#define ABILITY_HANGRY_MODE                 (ABILITIES_COUNT_CUSTOM + 26)
#define ABILITY_GIANT_WINGS                 (ABILITIES_COUNT_CUSTOM + 27)
#define ABILITY_HIBERNATE                   (ABILITIES_COUNT_CUSTOM + 28)
#define ABILITY_ICE_DEW                     (ABILITIES_COUNT_CUSTOM + 29)
#define ABILITY_ICE_SLIDING                 (ABILITIES_COUNT_CUSTOM + 30)
#define ABILITY_JUSTICE                     (ABILITIES_COUNT_CUSTOM + 31)
#define ABILITY_LEAD_COAT                   (ABILITIES_COUNT_CUSTOM + 32)
#define ABILITY_LAVAL_BODY                  (ABILITIES_COUNT_CUSTOM + 33)
#define ABILITY_MAGNET_FIELD                (ABILITIES_COUNT_CUSTOM + 34)
#define ABILITY_MOMENTUM                    (ABILITIES_COUNT_CUSTOM + 35)
#define ABILITY_MULTI_LIMBS                 (ABILITIES_COUNT_CUSTOM + 36)
#define ABILITY_PHANTOM                     (ABILITIES_COUNT_CUSTOM + 37)
#define ABILITY_PSY_BARRIER                 (ABILITIES_COUNT_CUSTOM + 38)
#define ABILITY_NIMBLE_FIST                 (ABILITIES_COUNT_CUSTOM + 39)
#define ABILITY_SOIL_ROOT                   (ABILITIES_COUNT_CUSTOM + 40)
#define ABILITY_SANDY_SURGE                 (ABILITIES_COUNT_CUSTOM + 41)
#define ABILITY_FORTITUDE                   (ABILITIES_COUNT_CUSTOM + 42)
#define ABILITY_DREAMCATCHER                (ABILITIES_COUNT_CUSTOM + 43)
#define ABILITY_JUGGERNAUT                  (ABILITIES_COUNT_CUSTOM + 44)
#define ABILITY_WEAKNESS_EXPLOIT            (ABILITIES_COUNT_CUSTOM + 45)
#define ABILITY_SOLENOGLYPHS                (ABILITIES_COUNT_CUSTOM + 46)
#define ABILITY_LEECH_FANGS                 (ABILITIES_COUNT_CUSTOM + 47)
#define ABILITY_SCAVENGER                   (ABILITIES_COUNT_CUSTOM + 48)
#define ABILITY_NOCTURNAL                   (ABILITIES_COUNT_CUSTOM + 49)
#define ABILITY_ETHEREAL                    (ABILITIES_COUNT_CUSTOM + 50)
#define ABILITY_OVERWHELM                   (ABILITIES_COUNT_CUSTOM + 51)
#define ABILITY_IMPENETRABLE                (ABILITIES_COUNT_CUSTOM + 52)
#define ABILITY_WAVE_SURF                   (ABILITIES_COUNT_CUSTOM + 53)
#define ABILITY_RAGING_STORM                (ABILITIES_COUNT_CUSTOM + 54)
#define ABILITY_METALLIC                    (ABILITIES_COUNT_CUSTOM + 55)
#define ABILITY_THICK_FLOSS                 (ABILITIES_COUNT_CUSTOM + 56)
#define ABILITY_LARGE_PETAL                 (ABILITIES_COUNT_CUSTOM + 57)
#define ABILITY_GRIP_PINCER                 (ABILITIES_COUNT_CUSTOM + 58)
#define ABILITY_FOSSILIZED                  (ABILITIES_COUNT_CUSTOM + 59)
#define ABILITY_SPEED_FORCE                 (ABILITIES_COUNT_CUSTOM + 60)
#define ABILITY_MAJESTIC_BIRD               (ABILITIES_COUNT_CUSTOM + 61)
#define ABILITY_COLD_SNAP                   (ABILITIES_COUNT_CUSTOM + 62)
#define ABILITY_NORTH_WIND                  (ABILITIES_COUNT_CUSTOM + 63)
#define ABILITY_POISON_ABSORB               (ABILITIES_COUNT_CUSTOM + 64)
#define ABILITY_PSYCHIC_BARRIER             (ABILITIES_COUNT_CUSTOM + 65)
#define ABILITY_SEA_GUARDIAN                (ABILITIES_COUNT_CUSTOM + 66)
#define ABILITY_SKY_GUARDIAN                (ABILITIES_COUNT_CUSTOM + 67)
#define ABILITY_SPATIAL_WARP                (ABILITIES_COUNT_CUSTOM + 68)
#define ABILITY_TEMPORAL_FLOW               (ABILITIES_COUNT_CUSTOM + 69)
#define ABILITY_BLOOD_LUST                  (ABILITIES_COUNT_CUSTOM + 70)
#define ABILITY_HEADACHE                    (ABILITIES_COUNT_CUSTOM + 71)
#define ABILITY_FIGHTING_SPIRIT             (ABILITIES_COUNT_CUSTOM + 72)
#define ABILITY_NULLIFY                     (ABILITIES_COUNT_CUSTOM + 73)
#define ABILITY_PSYCHIC_MIND                (ABILITIES_COUNT_CUSTOM + 74)
#define ABILITY_UNDYING                     (ABILITIES_COUNT_CUSTOM + 75)
#define ABILITY_SHALLOW_DIVER               (ABILITIES_COUNT_CUSTOM + 76)
#define ABILITY_MULTI_HEADED                (ABILITIES_COUNT_CUSTOM + 77)
#define ABILITY_POISONATE                   (ABILITIES_COUNT_CUSTOM + 78)
#define ABILITY_AMPLIFIER                   (ABILITIES_COUNT_CUSTOM + 79)
#define ABILITY_SEAWEED                     (ABILITIES_COUNT_CUSTOM + 80)
#define ABILITY_PETRIFIED_WOOD              (ABILITIES_COUNT_CUSTOM + 81)
#define ABILITY_PRESENCE_AURA               (ABILITIES_COUNT_CUSTOM + 82)
#define ABILITY_NINJA_STYLE                 (ABILITIES_COUNT_CUSTOM + 83)
#define ABILITY_PORTAL_HOOP                 (ABILITIES_COUNT_CUSTOM + 84)
#define ABILITY_WEATHERCAST                 (ABILITIES_COUNT_CUSTOM + 85)
#define ABILITY_WEATHER_CONTROL             (ABILITIES_COUNT_CUSTOM + 86)
#define ABILITY_PEEK_A_BOO                  (ABILITIES_COUNT_CUSTOM + 87)
#define ABILITY_LOOSING_QUILLS              (ABILITIES_COUNT_CUSTOM + 88)
#define ABILITY_FIELD_EXPLORER              (ABILITIES_COUNT_CUSTOM + 89)
#define ABILITY_AMPHIBIOUS                  (ABILITIES_COUNT_CUSTOM + 90)
#define ABILITY_KINGS_GRACE                 (ABILITIES_COUNT_CUSTOM + 91)
#define ABILITY_SPIDER_LAIR                 (ABILITIES_COUNT_CUSTOM + 92)
#define ABILITY_MAGICAL_DUST                (ABILITIES_COUNT_CUSTOM + 93)
#define ABILITY_DRAGONFLY                   (ABILITIES_COUNT_CUSTOM + 94)
#define ABILITY_AQUATIC                     (ABILITIES_COUNT_CUSTOM + 95)
#define ABILITY_LOUD_BANG                   (ABILITIES_COUNT_CUSTOM + 96)
#define ABILITY_COMMENSALISM                (ABILITIES_COUNT_CUSTOM + 97)
#define ABILITY_HEAVYWEIGHT                 (ABILITIES_COUNT_CUSTOM + 98)
#define ABILITY_BULLS_EYE                   (ABILITIES_COUNT_CUSTOM + 99)
#define ABILITY_MILK_MILKY                  (ABILITIES_COUNT_CUSTOM + 100)
#define ABILITY_LITTERING                   (ABILITIES_COUNT_CUSTOM + 101)
#define ABILITY_UNITY                       (ABILITIES_COUNT_CUSTOM + 102)
#define ABILITY_SWEET_DREAMS                (ABILITIES_COUNT_CUSTOM + 103)
#define ABILITY_VENOMOUS_SURGE              (ABILITIES_COUNT_CUSTOM + 104)
#define ABILITY_RAVINE_SURGE                (ABILITIES_COUNT_CUSTOM + 105)
#define ABILITY_SWAMP_SURGE                 (ABILITIES_COUNT_CUSTOM + 106)
#define ABILITY_FROZEN_SURGE                (ABILITIES_COUNT_CUSTOM + 107)
#define ABILITY_CHRISTMAS_SPIRIT            (ABILITIES_COUNT_CUSTOM + 108)
#define ABILITY_LIQUIFIED                   (ABILITIES_COUNT_CUSTOM + 109)
#define ABILITY_CHARGE_ATTACK               (ABILITIES_COUNT_CUSTOM + 110)
#define ABILITY_SUBTERRANEAN                (ABILITIES_COUNT_CUSTOM + 111)
#define ABILITY_BIRDS_OF_PREY               (ABILITIES_COUNT_CUSTOM + 112)
#define ABILITY_ELECTRIC_BURST              (ABILITIES_COUNT_CUSTOM + 113)
#define ABILITY_ABYSSAL_VOYAGER             (ABILITIES_COUNT_CUSTOM + 114)
#define ABILITY_CAMOUFLAGE                  (ABILITIES_COUNT_CUSTOM + 115)
#define ABILITY_INFLATABLE                  (ABILITIES_COUNT_CUSTOM + 116)
#define ABILITY_DISTORTION_WORLD            (ABILITIES_COUNT_CUSTOM + 117)
#define ABILITY_COIL_UP                     (ABILITIES_COUNT_CUSTOM + 118)
#define ABILITY_CINDER                      (ABILITIES_COUNT_CUSTOM + 119)
#define ABILITY_WATCHDOG                    (ABILITIES_COUNT_CUSTOM + 120)
#define ABILITY_SHOCK_ABSORTION             (ABILITIES_COUNT_CUSTOM + 121)
#define ABILITY_HAUNTED_SPIRIT              (ABILITIES_COUNT_CUSTOM + 122)
#define ABILITY_POWER_MODULATION            (ABILITIES_COUNT_CUSTOM + 123)
#define ABILITY_BLADEMASTER                 (ABILITIES_COUNT_CUSTOM + 124)
#define ABILITY_SAND_PLOW                   (ABILITIES_COUNT_CUSTOM + 125)
#define ABILITY_DESERT_SPIRIT               (ABILITIES_COUNT_CUSTOM + 126)
#define ABILITY_GROWING_TOOTH               (ABILITIES_COUNT_CUSTOM + 127)
#define ABILITY_ANCIENT_IDOL                (ABILITIES_COUNT_CUSTOM + 128)
#define ABILITY_ELECTROCYTES                (ABILITIES_COUNT_CUSTOM + 129)
#define ABILITY_MAJESTIC_MOTH               (ABILITIES_COUNT_CUSTOM + 130)
#define ABILITY_AURORA_BOREALIS             (ABILITIES_COUNT_CUSTOM + 131)
#define ABILITY_CRYSTALLIZE                 (ABILITIES_COUNT_CUSTOM + 132)
#define ABILITY_FRIGHTEN                    (ABILITIES_COUNT_CUSTOM + 133)
#define ABILITY_HYPNOTIST                   (ABILITIES_COUNT_CUSTOM + 134)
#define ABILITY_TOP_SPIN                    (ABILITIES_COUNT_CUSTOM + 135)
#define ABILITY_REFRACTION                  (ABILITIES_COUNT_CUSTOM + 136)
#define ABILITY_MIND_GAME                   (ABILITIES_COUNT_CUSTOM + 137)
#define ABILITY_AIR_BLOWER                  (ABILITIES_COUNT_CUSTOM + 138)
#define ABILITY_EARTHBOUND                  (ABILITIES_COUNT_CUSTOM + 139)
#define ABILITY_SOUL_EATER                  (ABILITIES_COUNT_CUSTOM + 140)
#define ABILITY_SHIELD_WALL                 (ABILITIES_COUNT_CUSTOM + 141)
#define ABILITY_DUAL_WIELDING               (ABILITIES_COUNT_CUSTOM + 142)
#define ABILITY_CORE_EXPOSURE               (ABILITIES_COUNT_CUSTOM + 143)
#define ABILITY_HALF_DRAKE                  (ABILITIES_COUNT_CUSTOM + 144)
#define ABILITY_HALF_DINO                   (ABILITIES_COUNT_CUSTOM + 145)
#define ABILITY_MUSCLE_GAUGE                (ABILITIES_COUNT_CUSTOM + 146)
#define ABILITY_TWISTED_DIMENSION           (ABILITIES_COUNT_CUSTOM + 147)
#define ABILITY_MOLTEN_DOWN                 (ABILITIES_COUNT_CUSTOM + 148)
#define ABILITY_CLAIRVOYANT                 (ABILITIES_COUNT_CUSTOM + 149)
#define ABILITY_MYSTIC_POWER                (ABILITIES_COUNT_CUSTOM + 150)
#define ABILITY_LIVID_SHADOW                (ABILITIES_COUNT_CUSTOM + 151)
#define ABILITY_DEATHLY_EMBRACE             (ABILITIES_COUNT_CUSTOM + 152)
#define ABILITY_MALEFICENT                  (ABILITIES_COUNT_CUSTOM + 153)
#define ABILITY_FIREBRINGER                 (ABILITIES_COUNT_CUSTOM + 154)
#define ABILITY_DRAGONSLAYER                (ABILITIES_COUNT_CUSTOM + 155)
#define ABILITY_REWIND                      (ABILITIES_COUNT_CUSTOM + 156)
#define ABILITY_ANTARTIC_BIRD               (ABILITIES_COUNT_CUSTOM + 157)
#define ABILITY_PERFECTIONIST               (ABILITIES_COUNT_CUSTOM + 158)
#define ABILITY_CELL_DIVISION               (ABILITIES_COUNT_CUSTOM + 159)
#define ABILITY_PSYCHO_SPIRAL               (ABILITIES_COUNT_CUSTOM + 160)
#define ABILITY_DARK_FLAMES                 (ABILITIES_COUNT_CUSTOM + 161)
#define ABILITY_SHARP_BLADES                (ABILITIES_COUNT_CUSTOM + 162)
#define ABILITY_BULLDOZER                   (ABILITIES_COUNT_CUSTOM + 163)
#define ABILITY_ROYAL_JELLY                 (ABILITIES_COUNT_CUSTOM + 164)
#define ABILITY_POWER_CORE                  (ABILITIES_COUNT_CUSTOM + 165)
#define ABILITY_STRETCHING_TONGUE           (ABILITIES_COUNT_CUSTOM + 166)
#define ABILITY_ANTEATER                    (ABILITIES_COUNT_CUSTOM + 167)
#define ABILITY_TRENCH                      (ABILITIES_COUNT_CUSTOM + 168)
#define ABILITY_GRAVITON_RAY                (ABILITIES_COUNT_CUSTOM + 169)
#define ABILITY_FORCE_OF_NATURE             (ABILITIES_COUNT_CUSTOM + 170)
#define ABILITY_BEWITCHING                  (ABILITIES_COUNT_CUSTOM + 171)
#define ABILITY_AFTERSHOCK                  (ABILITIES_COUNT_CUSTOM + 172)
#define ABILITY_SOLAR_FLARE                 (ABILITIES_COUNT_CUSTOM + 173)
#define ABILITY_LUNAR_ECLIPSE               (ABILITIES_COUNT_CUSTOM + 174)
#define ABILITY_SUGAR_RUSH                  (ABILITIES_COUNT_CUSTOM + 175)
#define ABILITY_POSSESSED                   (ABILITIES_COUNT_CUSTOM + 176)
#define ABILITY_YUKI_ONNA                   (ABILITIES_COUNT_CUSTOM + 177)
#define ABILITY_SIGHTING_SYSTEM             (ABILITIES_COUNT_CUSTOM + 178)
#define ABILITY_DRAGONATE                   (ABILITIES_COUNT_CUSTOM + 179)
#define ABILITY_BATESIAN_MIMICRY            (ABILITIES_COUNT_CUSTOM + 180)
#define ABILITY_CATS_LUCK                   (ABILITIES_COUNT_CUSTOM + 181)
#define ABILITY_BERSERKER_RAGE              (ABILITIES_COUNT_CUSTOM + 182)
#define ABILITY_RAGNAROK                    (ABILITIES_COUNT_CUSTOM + 183)
#define ABILITY_MACHINE_LEARNING            (ABILITIES_COUNT_CUSTOM + 184)
#define ABILITY_SINGER                      (ABILITIES_COUNT_CUSTOM + 185)
#define ABILITY_LIFE_FORCE_STEALER          (ABILITIES_COUNT_CUSTOM + 186)
#define ABILITY_STATS_SNATCHER              (ABILITIES_COUNT_CUSTOM + 187)
#define ABILITY_ANTI_UB                     (ABILITIES_COUNT_CUSTOM + 188)
#define ABILITY_CHIMERIC                    (ABILITIES_COUNT_CUSTOM + 189)
#define ABILITY_HITEN_MITSURUGI             (ABILITIES_COUNT_CUSTOM + 190)
#define ABILITY_RYUTSUISEN                  (ABILITIES_COUNT_CUSTOM + 191)
#define ABILITY_MASTER_OF_MIMICS            (ABILITIES_COUNT_CUSTOM + 192)
#define ABILITY_MYSTICAL_HORN               (ABILITIES_COUNT_CUSTOM + 193)
#define ABILITY_COLD_BLOODED                (ABILITIES_COUNT_CUSTOM + 194)
#define ABILITY_QUICK_CHARGE                (ABILITIES_COUNT_CUSTOM + 195)
#define ABILITY_FOREST_WITCH                (ABILITIES_COUNT_CUSTOM + 196)
#define ABILITY_DESTRUCTION_COCOON          (ABILITIES_COUNT_CUSTOM + 197)
#define ABILITY_APEX_PREDATOR               (ABILITIES_COUNT_CUSTOM + 198)
#define ABILITY_SILK_ARMOR                  (ABILITIES_COUNT_CUSTOM + 199)
#define ABILITY_ETERNAL_LIFE                (ABILITIES_COUNT_CUSTOM + 200)
#define ABILITY_ADAMANTIUM_SKIN             (ABILITIES_COUNT_CUSTOM + 201)
#define ABILITY_DEVOURER                    (ABILITIES_COUNT_CUSTOM + 202)
#define ABILITY_SIGHT_SHARING               (ABILITIES_COUNT_CUSTOM + 203)
#define ABILITY_SPELL_FIST                  (ABILITIES_COUNT_CUSTOM + 204)
#define ABILITY_FRICTION_MANE               (ABILITIES_COUNT_CUSTOM + 205)
#define ABILITY_THUNDERCLOUDS               (ABILITIES_COUNT_CUSTOM + 206)
#define ABILITY_METALMORPH                  (ABILITIES_COUNT_CUSTOM + 207)
#define ABILITY_TRAMPLE                     (ABILITIES_COUNT_CUSTOM + 208)
#define ABILITY_VOODOO_DOLL                 (ABILITIES_COUNT_CUSTOM + 209)
#define ABILITY_NIGHTFALL_LULLABY           (ABILITIES_COUNT_CUSTOM + 210)
#define ABILITY_LUNAR_VEIL                  (ABILITIES_COUNT_CUSTOM + 211)
#define ABILITY_PSYCHOKINETIC               (ABILITIES_COUNT_CUSTOM + 212)
#define ABILITY_PACK_TACTICS                (ABILITIES_COUNT_CUSTOM + 213)
#define ABILITY_PACK_LEADER                 (ABILITIES_COUNT_CUSTOM + 214)
#define ABILITY_X_RAY_VISION                (ABILITIES_COUNT_CUSTOM + 215)
#define ABILITY_LONELY_WOLF                 (ABILITIES_COUNT_CUSTOM + 216)
#define ABILITY_LUNAR_LUMINANCE             (ABILITIES_COUNT_CUSTOM + 217)
#define ABILITY_STELLAR_LUMINANCE           (ABILITIES_COUNT_CUSTOM + 218)
#define ABILITY_COSMIC_ENERGY               (ABILITIES_COUNT_CUSTOM + 219)
#define ABILITY_HERO_IN_TRAINING            (ABILITIES_COUNT_CUSTOM + 220)
#define ABILITY_GRANITIC_BODY               (ABILITIES_COUNT_CUSTOM + 221)
#define ABILITY_PYROCLASTIC                 (ABILITIES_COUNT_CUSTOM + 222)
#define ABILITY_HOLLOW_SHELL                (ABILITIES_COUNT_CUSTOM + 223)
#define ABILITY_PETRIFYING_GAZE             (ABILITIES_COUNT_CUSTOM + 224)
#define ABILITY_PATRIARCH                   (ABILITIES_COUNT_CUSTOM + 225)
#define ABILITY_MATRIARCH                   (ABILITIES_COUNT_CUSTOM + 226)
#define ABILITY_GEM_HOARDER                 (ABILITIES_COUNT_CUSTOM + 227)
#define ABILITY_CLEANSING_CHIME             (ABILITIES_COUNT_CUSTOM + 228)
#define ABILITY_JAW_TRAP                    (ABILITIES_COUNT_CUSTOM + 229)
#define ABILITY_POLARIZATION                (ABILITIES_COUNT_CUSTOM + 230)
#define ABILITY_WRESTLING_HEEL              (ABILITIES_COUNT_CUSTOM + 231)
#define ABILITY_PROVOKING_FEUDS             (ABILITIES_COUNT_CUSTOM + 232)
#define ABILITY_OUTBREAK                    (ABILITIES_COUNT_CUSTOM + 233)
#define ABILITY_PANDEMIC                    (ABILITIES_COUNT_CUSTOM + 234)
#define ABILITY_GRIMTOOTH                   (ABILITIES_COUNT_CUSTOM + 235)
#define ABILITY_SLOTTED_SHELL               (ABILITIES_COUNT_CUSTOM + 236)
#define ABILITY_TRAUMATIC_FIST              (ABILITIES_COUNT_CUSTOM + 237)
#define ABILITY_GOLDEN_ARMOR                (ABILITIES_COUNT_CUSTOM + 238)
#define ABILITY_ELEMENTIST                  (ABILITIES_COUNT_CUSTOM + 239)
#define ABILITY_GUARDIAN_DEITY              (ABILITIES_COUNT_CUSTOM + 240)
#define ABILITY_EVOBOOST_SYNC               (ABILITIES_COUNT_CUSTOM + 241)
#define ABILITY_DELUGE                      (ABILITIES_COUNT_CUSTOM + 242)
#define ABILITY_WILDFIRE                    (ABILITIES_COUNT_CUSTOM + 243)
#define ABILITY_BIOENGINEERING              (ABILITIES_COUNT_CUSTOM + 244)
#define ABILITY_AURORA_GUARD                (ABILITIES_COUNT_CUSTOM + 245)
#define ABILITY_PLAYFUL_AGGRO               (ABILITIES_COUNT_CUSTOM + 246)
#define ABILITY_FAIRY_TALES                 (ABILITIES_COUNT_CUSTOM + 247)
#define ABILITY_WITS_END                    (ABILITIES_COUNT_CUSTOM + 248)
#define ABILITY_MONSTROSITY_FUSION          (ABILITIES_COUNT_CUSTOM + 249)
#define ABILITY_LORD_SITH                   (ABILITIES_COUNT_CUSTOM + 250)
#define ABILITY_LIGHTSABER                  (ABILITIES_COUNT_CUSTOM + 251)
#define ABILITY_SHADOW_AURA                 (ABILITIES_COUNT_CUSTOM + 252)
#define ABILITY_GALE_OF_DARKNESS            (ABILITIES_COUNT_CUSTOM + 253)
#define ABILITY_DEFENSIVE_MANEUVER          (ABILITIES_COUNT_CUSTOM + 254)
#define ABILITY_SAVAGE_ATTACKER             (ABILITIES_COUNT_CUSTOM + 255)
#define ABILITY_HEAVILY_ARMOURED            (ABILITIES_COUNT_CUSTOM + 256)
#define ABILITY_EXOSKELETON                 (ABILITIES_COUNT_CUSTOM + 257)
#define ABILITY_CRUSTACEAN                  (ABILITIES_COUNT_CUSTOM + 258)
#define ABILITY_PHOTOVOLTAIC_FRILL          (ABILITIES_COUNT_CUSTOM + 259)
#define ABILITY_PLAY_DEAD                   (ABILITIES_COUNT_CUSTOM + 260)
#define ABILITY_FACE_SMUSHER                (ABILITIES_COUNT_CUSTOM + 261)
#define ABILITY_METAMORPHOSIS               (ABILITIES_COUNT_CUSTOM + 262)
#define ABILITY_OLD_SCHOOL                  (ABILITIES_COUNT_CUSTOM + 263)
#define ABILITY_MORE_POISON                 (ABILITIES_COUNT_CUSTOM + 264)
#define ABILITY_TIDE_WAITER                 (ABILITIES_COUNT_CUSTOM + 265)
#define ABILITY_VIBRATING_LUMBS             (ABILITIES_COUNT_CUSTOM + 266)
#define ABILITY_MUD_SHIELD                  (ABILITIES_COUNT_CUSTOM + 267)
#define ABILITY_OVERDOSE                    (ABILITIES_COUNT_CUSTOM + 268)
#define ABILITY_VICIOUSNESS                 (ABILITIES_COUNT_CUSTOM + 269)
#define ABILITY_ABSORB_ELEMENTS             (ABILITIES_COUNT_CUSTOM + 270)
#define ABILITY_DEEP_SEA_STAR               (ABILITIES_COUNT_CUSTOM + 271)
#define ABILITY_ARCTIC_FORCE                (ABILITIES_COUNT_CUSTOM + 272)
#define ABILITY_TENACITY                    (ABILITIES_COUNT_CUSTOM + 273)
#define ABILITY_FLOWER_GARDENER             (ABILITIES_COUNT_CUSTOM + 274)
#define ABILITY_FLASHING_FINS               (ABILITIES_COUNT_CUSTOM + 275)
#define ABILITY_DANCING_TENTACLES           (ABILITIES_COUNT_CUSTOM + 276)
#define ABILITY_CHAMPION_BELT               (ABILITIES_COUNT_CUSTOM + 277)
#define ABILITY_BONFIRE_BLOSSOM             (ABILITIES_COUNT_CUSTOM + 278)
#define ABILITY_BLACK_MAGICIAN              (ABILITIES_COUNT_CUSTOM + 279)
#define ABILITY_RESONANT_VOICE              (ABILITIES_COUNT_CUSTOM + 280)
#define ABILITY_CONNECTED_BRAINS            (ABILITIES_COUNT_CUSTOM + 281)
#define ABILITY_IRON_EATER                  (ABILITIES_COUNT_CUSTOM + 282)
#define ABILITY_ARMOR_CRACKER               (ABILITIES_COUNT_CUSTOM + 283)
#define ABILITY_DWARVEN_RESILIENCE          (ABILITIES_COUNT_CUSTOM + 284)
#define ABILITY_RED_HOT_CHILI_PEPPERS       (ABILITIES_COUNT_CUSTOM + 285)
#define ABILITY_TACTICAL_RETREAT            (ABILITIES_COUNT_CUSTOM + 286)
#define ABILITY_NEUTRINO_EXHAUST            (ABILITIES_COUNT_CUSTOM + 287)
#define ABILITY_HEAT_CARBURETTOR            (ABILITIES_COUNT_CUSTOM + 288)
#define ABILITY_KAMEN_RIDER                 (ABILITIES_COUNT_CUSTOM + 289)
#define ABILITY_ULTIMATE_SHOWDOWN           (ABILITIES_COUNT_CUSTOM + 290)
#define ABILITY_BATTLE_NETWORK              (ABILITIES_COUNT_CUSTOM + 291)
#define ABILITY_NOISE_CHANGE                (ABILITIES_COUNT_CUSTOM + 292)
#define ABILITY_CALL_REINFORCEMENT          (ABILITIES_COUNT_CUSTOM + 293)
#define ABILITY_SOLO_LEVELING               (ABILITIES_COUNT_CUSTOM + 294)

#define ABILITIES_COUNT                     (ABILITIES_COUNT_CUSTOM + 295)

#endif  // GUARD_CONSTANTS_ABILITIES_H
