#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0
// Balls
#define ITEM_MASTER_BALL 1
#define ITEM_ULTRA_BALL 2
#define ITEM_GREAT_BALL 3
#define ITEM_POKE_BALL 4
#define ITEM_SAFARI_BALL 5
#define ITEM_NET_BALL 6
#define ITEM_DIVE_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_REPEAT_BALL 9
#define ITEM_TIMER_BALL 10
#define ITEM_LUXURY_BALL 11
#define ITEM_DUSK_BALL 12
#define ITEM_HEAL_BALL 13
#define ITEM_QUICK_BALL 14
#define ITEM_CHERISH_BALL 15
#define ITEM_FAST_BALL 16
#define ITEM_LEVEL_BALL 17
#define ITEM_LURE_BALL 18
#define ITEM_HEAVY_BALL 19
#define ITEM_LOVE_BALL 20
#define ITEM_FRIEND_BALL 21
#define ITEM_MOON_BALL 22
#define ITEM_SPORT_BALL 23
#define ITEM_PARK_BALL 24
#define ITEM_DREAM_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_PREMIER_BALL 27

#define FIRST_BALL_INDEX          ITEM_MASTER_BALL
#define LAST_BALL_INDEX           ITEM_PREMIER_BALL

#define USABLE_ITEMS_START (LAST_BALL_INDEX + 1)
// Pokemon Items
#define ITEM_POTION (USABLE_ITEMS_START + 0)
#define ITEM_ANTIDOTE (USABLE_ITEMS_START + 1)
#define ITEM_BURN_HEAL (USABLE_ITEMS_START + 2)
#define ITEM_ICE_HEAL (USABLE_ITEMS_START + 3)
#define ITEM_AWAKENING (USABLE_ITEMS_START + 4)
#define ITEM_PARALYZE_HEAL (USABLE_ITEMS_START + 5)
#define ITEM_FULL_RESTORE (USABLE_ITEMS_START + 6)
#define ITEM_MAX_POTION (USABLE_ITEMS_START + 7)
#define ITEM_HYPER_POTION (USABLE_ITEMS_START + 8)
#define ITEM_SUPER_POTION (USABLE_ITEMS_START + 9)
#define ITEM_FULL_HEAL (USABLE_ITEMS_START + 10)
#define ITEM_REVIVE (USABLE_ITEMS_START + 11)
#define ITEM_MAX_REVIVE (USABLE_ITEMS_START + 12)
#define ITEM_FRESH_WATER (USABLE_ITEMS_START + 13)
#define ITEM_SODA_POP (USABLE_ITEMS_START + 14)
#define ITEM_LEMONADE (USABLE_ITEMS_START + 15)
#define ITEM_MOOMOO_MILK (USABLE_ITEMS_START + 16)
#define ITEM_ENERGY_POWDER (USABLE_ITEMS_START + 17)
#define ITEM_ENERGY_ROOT (USABLE_ITEMS_START + 18)
#define ITEM_HEAL_POWDER (USABLE_ITEMS_START + 19)
#define ITEM_REVIVAL_HERB (USABLE_ITEMS_START + 20)
#define ITEM_ETHER (USABLE_ITEMS_START + 21)
#define ITEM_MAX_ETHER (USABLE_ITEMS_START + 22)
#define ITEM_ELIXIR (USABLE_ITEMS_START + 23)
#define ITEM_MAX_ELIXIR (USABLE_ITEMS_START + 24)
#define ITEM_LAVA_COOKIE (USABLE_ITEMS_START + 25)
#define ITEM_BLUE_FLUTE (USABLE_ITEMS_START + 26)
#define ITEM_YELLOW_FLUTE (USABLE_ITEMS_START + 27)
#define ITEM_RED_FLUTE (USABLE_ITEMS_START + 28)
#define ITEM_BLACK_FLUTE (USABLE_ITEMS_START + 29)
#define ITEM_WHITE_FLUTE (USABLE_ITEMS_START + 30)
#define ITEM_BERRY_JUICE (USABLE_ITEMS_START + 31)
#define ITEM_SWEET_HEART (USABLE_ITEMS_START + 32)
#define ITEM_BIG_MALASADA (USABLE_ITEMS_START + 33)
#define ITEM_OLD_GATEAU (USABLE_ITEMS_START + 34)
#define ITEM_SACRED_ASH (USABLE_ITEMS_START + 35)
#define ITEM_RARE_CANDY (USABLE_ITEMS_START + 48)
#define ITEM_PP_UP (USABLE_ITEMS_START + 49)
#define ITEM_PP_MAX (USABLE_ITEMS_START + 50)
#define ITEM_GUARD_SPEC (USABLE_ITEMS_START + 51)
#define ITEM_DIRE_HIT (USABLE_ITEMS_START + 52)
#define ITEM_X_ATTACK (USABLE_ITEMS_START + 53)
#define ITEM_X_DEFENSE (USABLE_ITEMS_START + 54)
#define ITEM_X_SPEED (USABLE_ITEMS_START + 55)
#define ITEM_X_ACCURACY (USABLE_ITEMS_START + 56)
#define ITEM_X_SP_ATK (USABLE_ITEMS_START + 57)
#define ITEM_X_SP_DEF (USABLE_ITEMS_START + 58)
#define ITEM_POKE_DOLL (USABLE_ITEMS_START + 59)
#define ITEM_FLUFFY_TAIL (USABLE_ITEMS_START + 60)
#define ITEM_ESCAPE_ROPE (USABLE_ITEMS_START + 61)
#define ITEM_REPEL (USABLE_ITEMS_START + 62)
#define ITEM_SUPER_REPEL (USABLE_ITEMS_START + 63)
#define ITEM_MAX_REPEL (USABLE_ITEMS_START + 64)
#define ITEM_ABILITY_CAPSULE (USABLE_ITEMS_START + 65)
#define ITEM_ABILITY_PATCH (USABLE_ITEMS_START + 66)

#define USABLE_ITEMS_END (ITEM_ABILITY_PATCH)

#define MEDICINE_ITEMS_START (USABLE_ITEMS_END + 1)
//EV medicine
#define ITEM_HP_UP (MEDICINE_ITEMS_START + 0)
#define ITEM_PROTEIN (MEDICINE_ITEMS_START + 1)
#define ITEM_IRON (MEDICINE_ITEMS_START + 2)
#define ITEM_CARBOS (MEDICINE_ITEMS_START + 3)
#define ITEM_CALCIUM (MEDICINE_ITEMS_START + 4)
#define ITEM_ZINC (MEDICINE_ITEMS_START + 5)

#define MEDICINE_ITEMS_END (ITEM_ZINC)

#define FEATHER_ITEMS_START (MEDICINE_ITEMS_END + 1)
// Wings
#define ITEM_HEALTH_FEATHER (FEATHER_ITEMS_START + 0)
#define ITEM_MUSCLE_FEATHER (FEATHER_ITEMS_START + 1)
#define ITEM_RESIST_FEATHER (FEATHER_ITEMS_START + 2)
#define ITEM_GENIUS_FEATHER (FEATHER_ITEMS_START + 3)
#define ITEM_CLEVER_FEATHER (FEATHER_ITEMS_START + 4)
#define ITEM_SWIFT_FEATHER (FEATHER_ITEMS_START + 5)
#define ITEM_PRETTY_FEATHER (FEATHER_ITEMS_START + 6)

#define FEATHER_ITEMS_END (ITEM_PRETTY_FEATHER)

#define UNUSABLE_ITEMS_START (FEATHER_ITEMS_END + 1)
// Unusable
#define ITEM_RED_APRICORN (UNUSABLE_ITEMS_START + 0)
#define ITEM_BLUE_APRICORN (UNUSABLE_ITEMS_START + 1)
#define ITEM_YELLOW_APRICORN (UNUSABLE_ITEMS_START + 2)
#define ITEM_GREEN_APRICORN (UNUSABLE_ITEMS_START + 3)
#define ITEM_PINK_APRICORN (UNUSABLE_ITEMS_START + 4)
#define ITEM_WHITE_APRICORN (UNUSABLE_ITEMS_START + 5)
#define ITEM_BLACK_APRICORN (UNUSABLE_ITEMS_START + 6)
#define ITEM_TINY_MUSHROOM (UNUSABLE_ITEMS_START + 7)
#define ITEM_BIG_MUSHROOM (UNUSABLE_ITEMS_START + 8)
#define ITEM_PEARL (UNUSABLE_ITEMS_START + 9)
#define ITEM_BIG_PEARL (UNUSABLE_ITEMS_START + 10)
#define ITEM_STARDUST (UNUSABLE_ITEMS_START + 11)
#define ITEM_STAR_PIECE (UNUSABLE_ITEMS_START + 12)
#define ITEM_NUGGET (UNUSABLE_ITEMS_START + 13)
#define ITEM_HEART_SCALE (UNUSABLE_ITEMS_START + 14)
#define ITEM_RED_NECTAR (UNUSABLE_ITEMS_START + 15)
#define ITEM_YELLOW_NECTAR (UNUSABLE_ITEMS_START + 16)
#define ITEM_PINK_NECTAR (UNUSABLE_ITEMS_START + 17)
#define ITEM_PURPLE_NECTAR (UNUSABLE_ITEMS_START + 18)
#define ITEM_HONEY (UNUSABLE_ITEMS_START + 19)
#define ITEM_RARE_BONE (UNUSABLE_ITEMS_START + 20)
#define ITEM_GALARICA_TWIG (UNUSABLE_ITEMS_START + 21)
#define ITEM_SHOAL_SALT (UNUSABLE_ITEMS_START + 22)
#define ITEM_SHOAL_SHELL (UNUSABLE_ITEMS_START + 23)
#define ITEM_RED_SHARD (UNUSABLE_ITEMS_START + 24)
#define ITEM_BLUE_SHARD (UNUSABLE_ITEMS_START + 25)
#define ITEM_YELLOW_SHARD (UNUSABLE_ITEMS_START + 26)
#define ITEM_GREEN_SHARD (UNUSABLE_ITEMS_START + 27)

#define UNUSABLE_ITEMS_END (ITEM_GREEN_SHARD)

#define MAIL_ITEMS_START (UNUSABLE_ITEMS_END + 1)
// Mails
#define ITEM_ORANGE_MAIL (MAIL_ITEMS_START + 0)
#define ITEM_HARBOR_MAIL (MAIL_ITEMS_START + 1)
#define ITEM_GLITTER_MAIL (MAIL_ITEMS_START + 2)
#define ITEM_MECH_MAIL (MAIL_ITEMS_START + 3)
#define ITEM_WOOD_MAIL (MAIL_ITEMS_START + 4)
#define ITEM_WAVE_MAIL (MAIL_ITEMS_START + 5)
#define ITEM_BEAD_MAIL (MAIL_ITEMS_START + 6)
#define ITEM_SHADOW_MAIL (MAIL_ITEMS_START + 7)
#define ITEM_TROPIC_MAIL (MAIL_ITEMS_START + 8)
#define ITEM_DREAM_MAIL (MAIL_ITEMS_START + 9)
#define ITEM_FAB_MAIL (MAIL_ITEMS_START + 10)
#define ITEM_RETRO_MAIL (MAIL_ITEMS_START + 11)

#define FIRST_MAIL_INDEX    ITEM_ORANGE_MAIL
#define LAST_MAIL_INDEX     ITEM_RETRO_MAIL

#define BERRIES_ITEMS_START (LAST_MAIL_INDEX + 1)
// Berries
#define ITEM_CHERI_BERRY (BERRIES_ITEMS_START + 0)
#define ITEM_CHESTO_BERRY (BERRIES_ITEMS_START + 1)
#define ITEM_PECHA_BERRY (BERRIES_ITEMS_START + 2)
#define ITEM_RAWST_BERRY (BERRIES_ITEMS_START + 3)
#define ITEM_ASPEAR_BERRY (BERRIES_ITEMS_START + 4)
#define ITEM_LEPPA_BERRY (BERRIES_ITEMS_START + 5)
#define ITEM_ORAN_BERRY (BERRIES_ITEMS_START + 6)
#define ITEM_PERSIM_BERRY (BERRIES_ITEMS_START + 7)
#define ITEM_LUM_BERRY (BERRIES_ITEMS_START + 8)
#define ITEM_SITRUS_BERRY (BERRIES_ITEMS_START + 9)
#define ITEM_FIGY_BERRY (BERRIES_ITEMS_START + 10)
#define ITEM_WIKI_BERRY (BERRIES_ITEMS_START + 11)
#define ITEM_MAGO_BERRY (BERRIES_ITEMS_START + 12)
#define ITEM_AGUAV_BERRY (BERRIES_ITEMS_START + 13)
#define ITEM_IAPAPA_BERRY (BERRIES_ITEMS_START + 14)
#define ITEM_RAZZ_BERRY (BERRIES_ITEMS_START + 15)
#define ITEM_BLUK_BERRY (BERRIES_ITEMS_START + 16)
#define ITEM_NANAB_BERRY (BERRIES_ITEMS_START + 17)
#define ITEM_WEPEAR_BERRY (BERRIES_ITEMS_START + 18)
#define ITEM_PINAP_BERRY (BERRIES_ITEMS_START + 19)
#define ITEM_POMEG_BERRY (BERRIES_ITEMS_START + 20)
#define ITEM_KELPSY_BERRY (BERRIES_ITEMS_START + 21)
#define ITEM_QUALOT_BERRY (BERRIES_ITEMS_START + 22)
#define ITEM_HONDEW_BERRY (BERRIES_ITEMS_START + 23)
#define ITEM_GREPA_BERRY (BERRIES_ITEMS_START + 24)
#define ITEM_TAMATO_BERRY (BERRIES_ITEMS_START + 25)
#define ITEM_CORNN_BERRY (BERRIES_ITEMS_START + 26)
#define ITEM_MAGOST_BERRY (BERRIES_ITEMS_START + 27)
#define ITEM_RABUTA_BERRY (BERRIES_ITEMS_START + 28)
#define ITEM_NOMEL_BERRY (BERRIES_ITEMS_START + 29)
#define ITEM_SPELON_BERRY (BERRIES_ITEMS_START + 30)
#define ITEM_PAMTRE_BERRY (BERRIES_ITEMS_START + 31)
#define ITEM_WATMEL_BERRY (BERRIES_ITEMS_START + 32)
#define ITEM_DURIN_BERRY (BERRIES_ITEMS_START + 33)
#define ITEM_BELUE_BERRY (BERRIES_ITEMS_START + 34)
//All berries halves damage
#define ITEM_OCCA_BERRY (BERRIES_ITEMS_START + 35)
#define ITEM_PASSHO_BERRY (BERRIES_ITEMS_START + 36)
#define ITEM_WACAN_BERRY (BERRIES_ITEMS_START + 37)
#define ITEM_RINDO_BERRY (BERRIES_ITEMS_START + 38)
#define ITEM_YACHE_BERRY (BERRIES_ITEMS_START + 39)
#define ITEM_CHOPLE_BERRY (BERRIES_ITEMS_START + 40)
#define ITEM_KEBIA_BERRY (BERRIES_ITEMS_START + 41)
#define ITEM_SHUCA_BERRY (BERRIES_ITEMS_START + 42)
#define ITEM_COBA_BERRY (BERRIES_ITEMS_START + 43)
#define ITEM_PAYAPA_BERRY (BERRIES_ITEMS_START + 44)
#define ITEM_TANGA_BERRY (BERRIES_ITEMS_START + 45)
#define ITEM_CHARTI_BERRY (BERRIES_ITEMS_START + 46)
#define ITEM_KASIB_BERRY (BERRIES_ITEMS_START + 47)
#define ITEM_HABAN_BERRY (BERRIES_ITEMS_START + 48)
#define ITEM_COLBUR_BERRY (BERRIES_ITEMS_START + 49)
#define ITEM_BABIRI_BERRY (BERRIES_ITEMS_START + 50)
#define ITEM_CHILAN_BERRY (BERRIES_ITEMS_START + 51)
#define ITEM_ROSELI_BERRY (BERRIES_ITEMS_START + 52)
#define ITEM_LIECHI_BERRY (BERRIES_ITEMS_START + 53)
#define ITEM_GANLON_BERRY (BERRIES_ITEMS_START + 54)
#define ITEM_SALAC_BERRY (BERRIES_ITEMS_START + 55)
#define ITEM_PETAYA_BERRY (BERRIES_ITEMS_START + 56)
#define ITEM_APICOT_BERRY (BERRIES_ITEMS_START + 57)
#define ITEM_LANSAT_BERRY (BERRIES_ITEMS_START + 58)
#define ITEM_STARF_BERRY (BERRIES_ITEMS_START + 59)
#define ITEM_MICLE_BERRY (BERRIES_ITEMS_START + 60)
#define ITEM_ENIGMA_BERRY (BERRIES_ITEMS_START + 61)
#define ITEM_CUSTAP_BERRY (BERRIES_ITEMS_START + 62)
#define ITEM_JABOCA_BERRY (BERRIES_ITEMS_START + 63)
#define ITEM_ROWAP_BERRY (BERRIES_ITEMS_START + 64)
#define ITEM_KEE_BERRY (BERRIES_ITEMS_START + 65)
#define ITEM_MARANGA_BERRY (BERRIES_ITEMS_START + 66)

#define FIRST_BERRY_INDEX           ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX            ITEM_MARANGA_BERRY

#define HELD_EFFECT_ITEMS_START (LAST_BERRY_INDEX + 1)
// Held effect items
#define ITEM_BRIGHT_POWDER (HELD_EFFECT_ITEMS_START + 0)
#define ITEM_WHITE_HERB (HELD_EFFECT_ITEMS_START + 1)
#define ITEM_MACHO_BRACE (HELD_EFFECT_ITEMS_START + 2)
#define ITEM_EXP_SHARE (HELD_EFFECT_ITEMS_START + 3)
#define ITEM_QUICK_CLAW (HELD_EFFECT_ITEMS_START + 4)
#define ITEM_SOOTHE_BELL (HELD_EFFECT_ITEMS_START + 5)
#define ITEM_MENTAL_HERB (HELD_EFFECT_ITEMS_START + 6)
#define ITEM_CHOICE_BAND (HELD_EFFECT_ITEMS_START + 7)
#define ITEM_SILVER_POWDER (HELD_EFFECT_ITEMS_START + 8)
#define ITEM_AMULET_COIN (HELD_EFFECT_ITEMS_START + 9)
#define ITEM_CLEANSE_TAG (HELD_EFFECT_ITEMS_START + 10)
#define ITEM_SMOKE_BALL (HELD_EFFECT_ITEMS_START + 11)
#define ITEM_EVERSTONE (HELD_EFFECT_ITEMS_START + 12)
#define ITEM_FOCUS_BAND (HELD_EFFECT_ITEMS_START + 13)
#define ITEM_LUCKY_EGG (HELD_EFFECT_ITEMS_START + 14)
#define ITEM_SCOPE_LENS (HELD_EFFECT_ITEMS_START + 15)
#define ITEM_LEFTOVERS (HELD_EFFECT_ITEMS_START + 16)
#define ITEM_SHELL_BELL (HELD_EFFECT_ITEMS_START + 17)
#define ITEM_POWER_HERB (HELD_EFFECT_ITEMS_START + 18)
#define ITEM_CHOICE_SCARF (HELD_EFFECT_ITEMS_START + 19)
#define ITEM_CHOICE_SPECS (HELD_EFFECT_ITEMS_START + 20)
#define ITEM_FOCUS_SASH (HELD_EFFECT_ITEMS_START + 21)
#define ITEM_WIDE_LENS (HELD_EFFECT_ITEMS_START + 22)
#define ITEM_ZOOM_LENS (HELD_EFFECT_ITEMS_START + 23)
#define ITEM_METRONOME (HELD_EFFECT_ITEMS_START + 24)
#define ITEM_MUSCLE_BAND (HELD_EFFECT_ITEMS_START + 25)
#define ITEM_WISE_GLASSES (HELD_EFFECT_ITEMS_START + 26)
#define ITEM_EXPERT_BELT (HELD_EFFECT_ITEMS_START + 27)
#define ITEM_LIGHT_CLAY (HELD_EFFECT_ITEMS_START + 28)
#define ITEM_ICY_ROCK (HELD_EFFECT_ITEMS_START + 29)
#define ITEM_SMOOTH_ROCK (HELD_EFFECT_ITEMS_START + 30)
#define ITEM_HEAT_ROCK (HELD_EFFECT_ITEMS_START + 31)
#define ITEM_DAMP_ROCK (HELD_EFFECT_ITEMS_START + 32)
#define ITEM_DESTINY_KNOT (HELD_EFFECT_ITEMS_START + 33)
#define ITEM_GRIP_CLAW (HELD_EFFECT_ITEMS_START + 34)
#define ITEM_LIFE_ORB (HELD_EFFECT_ITEMS_START + 35)
#define ITEM_TOXIC_ORB (HELD_EFFECT_ITEMS_START + 36)
#define ITEM_FLAME_ORB (HELD_EFFECT_ITEMS_START + 37)
#define ITEM_STICKY_BARB (HELD_EFFECT_ITEMS_START + 38)
#define ITEM_BLACK_SLUDGE (HELD_EFFECT_ITEMS_START + 39)
#define ITEM_IRON_BALL (HELD_EFFECT_ITEMS_START + 40)
#define ITEM_LAGGING_TAIL (HELD_EFFECT_ITEMS_START + 41)
#define ITEM_SHED_SHELL (HELD_EFFECT_ITEMS_START + 42)
#define ITEM_BIG_ROOT (HELD_EFFECT_ITEMS_START + 43)
#define ITEM_EVIOLITE (HELD_EFFECT_ITEMS_START + 44)
#define ITEM_FLOAT_STONE (HELD_EFFECT_ITEMS_START + 45)
#define ITEM_ROCKY_HELMET (HELD_EFFECT_ITEMS_START + 46)
#define ITEM_AIR_BALLOON (HELD_EFFECT_ITEMS_START + 47)
#define ITEM_RED_CARD (HELD_EFFECT_ITEMS_START + 48)
#define ITEM_RING_TARGET (HELD_EFFECT_ITEMS_START + 49)
#define ITEM_BINDING_BAND (HELD_EFFECT_ITEMS_START + 50)
#define ITEM_EJECT_BUTTON (HELD_EFFECT_ITEMS_START + 51)
#define ITEM_ABSORB_BULB (HELD_EFFECT_ITEMS_START + 52)
#define ITEM_CELL_BATTERY (HELD_EFFECT_ITEMS_START + 53)
#define ITEM_LUMINOUS_MOSS (HELD_EFFECT_ITEMS_START + 54)
#define ITEM_SNOWBALL (HELD_EFFECT_ITEMS_START + 55)
#define ITEM_WEAKNESS_POLICY (HELD_EFFECT_ITEMS_START + 56)
#define ITEM_ASSAULT_VEST (HELD_EFFECT_ITEMS_START + 57)
#define ITEM_SAFETY_GOGGLES (HELD_EFFECT_ITEMS_START + 58)
#define ITEM_ADRENALINE_ORB (HELD_EFFECT_ITEMS_START + 59)
#define ITEM_TERRAIN_EXTENDER (HELD_EFFECT_ITEMS_START + 60)
#define ITEM_PROTECTIVE_PADS (HELD_EFFECT_ITEMS_START + 61)
#define ITEM_EJECT_PACK (HELD_EFFECT_ITEMS_START + 62)
#define ITEM_THROAT_SPRAY (HELD_EFFECT_ITEMS_START + 63)
#define ITEM_HEAVY_DUTY_BOOTS (HELD_EFFECT_ITEMS_START + 64)
#define ITEM_BLUNDER_POLICY (HELD_EFFECT_ITEMS_START + 65)
#define ITEM_ROOM_SERVICE (HELD_EFFECT_ITEMS_START + 66)
#define ITEM_UTILITY_UMBRELLA (HELD_EFFECT_ITEMS_START + 67)
#define ITEM_BERSERK_GENE (HELD_EFFECT_ITEMS_START + 68)
#define ITEM_ABILITY_SHIELD (HELD_EFFECT_ITEMS_START + 69)
#define ITEM_CLEAR_AMULET (HELD_EFFECT_ITEMS_START + 70)
#define ITEM_PUNCHING_GLOVE (HELD_EFFECT_ITEMS_START + 71)
#define ITEM_COVERT_CLOAK (HELD_EFFECT_ITEMS_START + 72)
#define ITEM_LOADED_DICE (HELD_EFFECT_ITEMS_START + 73)
#define ITEM_BOOSTER_ENERGY (HELD_EFFECT_ITEMS_START + 74)
#define ITEM_MIRROR_HERB (HELD_EFFECT_ITEMS_START + 75)

#define HELD_EFFECT_ITEMS_END (ITEM_MIRROR_HERB)

#define EV_TRAINING_ITEMS_START (HELD_EFFECT_ITEMS_END + 1)
// Ev Training items
#define ITEM_POWER_BRACER (EV_TRAINING_ITEMS_START + 0)
#define ITEM_POWER_BELT (EV_TRAINING_ITEMS_START + 1)
#define ITEM_POWER_LENS (EV_TRAINING_ITEMS_START + 2)
#define ITEM_POWER_BAND (EV_TRAINING_ITEMS_START + 3)
#define ITEM_POWER_ANKLET (EV_TRAINING_ITEMS_START + 4)
#define ITEM_POWER_WEIGHT (EV_TRAINING_ITEMS_START + 5)

#define EV_TRAINING_ITEMS_END (ITEM_POWER_WEIGHT)

#define TYPE_BOOSTING_ITEMS_START (EV_TRAINING_ITEMS_END + 1)
// Type Boosting items
#define ITEM_METAL_COAT (TYPE_BOOSTING_ITEMS_START + 0)
#define ITEM_SOFT_SAND (TYPE_BOOSTING_ITEMS_START + 1)
#define ITEM_HARD_STONE (TYPE_BOOSTING_ITEMS_START + 2)
#define ITEM_MIRACLE_SEED (TYPE_BOOSTING_ITEMS_START + 3)
#define ITEM_BLACK_GLASSES (TYPE_BOOSTING_ITEMS_START + 4)
#define ITEM_BLACK_BELT (TYPE_BOOSTING_ITEMS_START + 5)
#define ITEM_MAGNET (TYPE_BOOSTING_ITEMS_START + 6)
#define ITEM_MYSTIC_WATER (TYPE_BOOSTING_ITEMS_START + 7)
#define ITEM_SHARP_BEAK (TYPE_BOOSTING_ITEMS_START + 8)
#define ITEM_POISON_BARB (TYPE_BOOSTING_ITEMS_START + 9)
#define ITEM_NEVER_MELT_ICE (TYPE_BOOSTING_ITEMS_START + 10)
#define ITEM_SPELL_TAG (TYPE_BOOSTING_ITEMS_START + 11)
#define ITEM_TWISTED_SPOON (TYPE_BOOSTING_ITEMS_START + 12)
#define ITEM_CHARCOAL (TYPE_BOOSTING_ITEMS_START + 13)
#define ITEM_DRAGON_FANG (TYPE_BOOSTING_ITEMS_START + 14)
#define ITEM_SILK_SCARF (TYPE_BOOSTING_ITEMS_START + 15)
#define ITEM_FAIRY_FEATHER (TYPE_BOOSTING_ITEMS_START + 16)

#define TYPE_BOOSTING_ITEMS_END (ITEM_FAIRY_FEATHER)

#define TERRAIN_SEEDS_START (TYPE_BOOSTING_ITEMS_END + 1)
// Seeds
#define ITEM_ELECTRIC_SEED (TERRAIN_SEEDS_START + 0)
#define ITEM_PSYCHIC_SEED (TERRAIN_SEEDS_START + 1)
#define ITEM_MISTY_SEED (TERRAIN_SEEDS_START + 2)
#define ITEM_GRASSY_SEED (TERRAIN_SEEDS_START + 3)

#define TERRAIN_SEEDS_END (ITEM_GRASSY_SEED)

#define INCENSES_START (TERRAIN_SEEDS_END + 1)
// Incenses
#define ITEM_SEA_INCENSE (INCENSES_START + 0)
#define ITEM_LAX_INCENSE (INCENSES_START + 1)
#define ITEM_ODD_INCENSE (INCENSES_START + 2)
#define ITEM_ROCK_INCENSE (INCENSES_START + 3)
#define ITEM_FULL_INCENSE (INCENSES_START + 4)
#define ITEM_WAVE_INCENSE (INCENSES_START + 5)
#define ITEM_ROSE_INCENSE (INCENSES_START + 6)
#define ITEM_LUCK_INCENSE (INCENSES_START + 7)
#define ITEM_PURE_INCENSE (INCENSES_START + 8)

#define INCENSES_END (ITEM_PURE_INCENSE)

#define GEMS_START (INCENSES_END + 1)
// Gems
#define ITEM_BUG_GEM (GEMS_START + 0)
#define ITEM_DARK_GEM (GEMS_START + 1)
#define ITEM_DRAGON_GEM (GEMS_START + 2)
#define ITEM_ELECTRIC_GEM (GEMS_START + 3)
#define ITEM_FAIRY_GEM (GEMS_START + 4)
#define ITEM_FIGHTING_GEM (GEMS_START + 5)
#define ITEM_FIRE_GEM (GEMS_START + 6)
#define ITEM_FLYING_GEM (GEMS_START + 7)
#define ITEM_GHOST_GEM (GEMS_START + 8)
#define ITEM_GRASS_GEM (GEMS_START + 9)
#define ITEM_GROUND_GEM (GEMS_START + 10)
#define ITEM_ICE_GEM (GEMS_START + 11)
#define ITEM_NORMAL_GEM (GEMS_START + 12)
#define ITEM_POISON_GEM (GEMS_START + 13)
#define ITEM_PSYCHIC_GEM (GEMS_START + 14)
#define ITEM_ROCK_GEM (GEMS_START + 15)
#define ITEM_STEEL_GEM (GEMS_START + 16)
#define ITEM_WATER_GEM (GEMS_START + 17)

#define GEMS_END (ITEM_WATER_GEM)

#define CONTEST_SCARFS_START (GEMS_END + 1)
// Contest held items
#define ITEM_RED_SCARF (CONTEST_SCARFS_START + 0)
#define ITEM_BLUE_SCARF (CONTEST_SCARFS_START + 1)
#define ITEM_PINK_SCARF (CONTEST_SCARFS_START + 2)
#define ITEM_GREEN_SCARF (CONTEST_SCARFS_START + 3)
#define ITEM_YELLOW_SCARF (CONTEST_SCARFS_START + 4)

#define CONTEST_SCARFS_END (ITEM_YELLOW_SCARF)

#define MINTS_START (CONTEST_SCARFS_END + 1)
// Mints
#define ITEM_ADAMANT_MINT (MINTS_START + 0)
#define ITEM_BOLD_MINT (MINTS_START + 1)
#define ITEM_BRAVE_MINT (MINTS_START + 2)
#define ITEM_CALM_MINT (MINTS_START + 3)
#define ITEM_CAREFUL_MINT (MINTS_START + 4)
#define ITEM_GENTLE_MINT (MINTS_START + 5)
#define ITEM_HASTY_MINT (MINTS_START + 6)
#define ITEM_IMPISH_MINT (MINTS_START + 7)
#define ITEM_JOLLY_MINT (MINTS_START + 8)
#define ITEM_LAX_MINT (MINTS_START + 9)
#define ITEM_LONELY_MINT (MINTS_START + 10)
#define ITEM_MILD_MINT (MINTS_START + 11)
#define ITEM_MODEST_MINT (MINTS_START + 12)
#define ITEM_NAIVE_MINT (MINTS_START + 13)
#define ITEM_NAUGHTY_MINT (MINTS_START + 14)
#define ITEM_QUIET_MINT (MINTS_START + 15)
#define ITEM_RASH_MINT (MINTS_START + 16)
#define ITEM_RELAXED_MINT (MINTS_START + 17)
#define ITEM_SASSY_MINT (MINTS_START + 18)
#define ITEM_SERIOUS_MINT (MINTS_START + 19)
#define ITEM_TIMID_MINT (MINTS_START + 20)

#define MINTS_END (ITEM_TIMID_MINT)

#define KEY_ITEMS_START (MINTS_END + 1)
// Key Items
#define ITEM_MACH_BIKE (KEY_ITEMS_START + 0)
#define ITEM_COIN_CASE (KEY_ITEMS_START + 1)
#define ITEM_ITEMFINDER (KEY_ITEMS_START + 2)
#define ITEM_OLD_ROD (KEY_ITEMS_START + 3)
#define ITEM_GOOD_ROD (KEY_ITEMS_START + 4)
#define ITEM_SUPER_ROD (KEY_ITEMS_START + 5)
#define ITEM_SS_TICKET (KEY_ITEMS_START + 6)
#define ITEM_CONTEST_PASS (KEY_ITEMS_START + 7)
#define ITEM_WAILMER_PAIL (KEY_ITEMS_START + 8)
#define ITEM_DEVON_GOODS (KEY_ITEMS_START + 9)
#define ITEM_SOOT_SACK (KEY_ITEMS_START + 10)
#define ITEM_BASEMENT_KEY (KEY_ITEMS_START + 11)
#define ITEM_ACRO_BIKE (KEY_ITEMS_START + 12)
#define ITEM_POKEBLOCK_CASE (KEY_ITEMS_START + 13)
#define ITEM_LETTER (KEY_ITEMS_START + 14)
#define ITEM_EON_TICKET (KEY_ITEMS_START + 15)
#define ITEM_SCANNER (KEY_ITEMS_START + 18)
#define ITEM_GO_GOGGLES (KEY_ITEMS_START + 19)
#define ITEM_METEORITE (KEY_ITEMS_START + 20)
#define ITEM_ROOM_1_KEY (KEY_ITEMS_START + 21)
#define ITEM_ROOM_2_KEY (KEY_ITEMS_START + 22)
#define ITEM_ROOM_4_KEY (KEY_ITEMS_START + 23)
#define ITEM_ROOM_6_KEY (KEY_ITEMS_START + 24)
#define ITEM_STORAGE_KEY (KEY_ITEMS_START + 25)
#define ITEM_DEVON_SCOPE (KEY_ITEMS_START + 26)
#define ITEM_ROTOM_CATALOG (KEY_ITEMS_START + 27)
#define ITEM_REVEAL_GLASS (KEY_ITEMS_START + 28)
#define ITEM_DNA_SPLICERS (KEY_ITEMS_START + 29)
#define ITEM_ZYGARDE_CUBE (KEY_ITEMS_START + 30)
#define ITEM_PRISON_BOTTLE (KEY_ITEMS_START + 31)
#define ITEM_N_SOLARIZER (KEY_ITEMS_START + 32)
#define ITEM_N_LUNARIZER (KEY_ITEMS_START + 33)
#define ITEM_REINS_OF_UNITY (KEY_ITEMS_START + 34)
#define ITEM_MAGMA_STONE (KEY_ITEMS_START + 35)
#define ITEM_RED_SCALE (KEY_ITEMS_START + 36)
#define ITEM_CLEAR_BELL (KEY_ITEMS_START + 37)
#define ITEM_RUNNING_SHOES (KEY_ITEMS_START + 38)
#define ITEM_OAKS_PARCEL (KEY_ITEMS_START + 39)
#define ITEM_POKE_FLUTE (KEY_ITEMS_START + 40)
#define ITEM_SECRET_KEY (KEY_ITEMS_START + 41)
#define ITEM_BIKE_VOUCHER (KEY_ITEMS_START + 42)
#define ITEM_GOLD_TEETH (KEY_ITEMS_START + 43)
#define ITEM_OLD_AMBER (KEY_ITEMS_START + 44)
#define ITEM_CARD_KEY (KEY_ITEMS_START + 45)
#define ITEM_LIFT_KEY (KEY_ITEMS_START + 46)
#define ITEM_SILPH_SCOPE (KEY_ITEMS_START + 47)
#define ITEM_BICYCLE (KEY_ITEMS_START + 48)
#define ITEM_TOWN_MAP (KEY_ITEMS_START + 49)
#define ITEM_VS_SEEKER (KEY_ITEMS_START + 50)
#define ITEM_FAME_CHECKER (KEY_ITEMS_START + 51)
#define ITEM_TM_CASE (KEY_ITEMS_START + 52)
#define ITEM_BERRY_POUCH (KEY_ITEMS_START + 53)
#define ITEM_TEACHY_TV (KEY_ITEMS_START + 54)
#define ITEM_TRI_PASS (KEY_ITEMS_START + 55)
#define ITEM_RAINBOW_PASS (KEY_ITEMS_START + 56)
#define ITEM_TEA (KEY_ITEMS_START + 57)
#define ITEM_MYSTIC_TICKET (KEY_ITEMS_START + 58)
#define ITEM_AURORA_TICKET (KEY_ITEMS_START + 59)
#define ITEM_POWDER_JAR (KEY_ITEMS_START + 60)
#define ITEM_RUBY (KEY_ITEMS_START + 61)
#define ITEM_SAPPHIRE (KEY_ITEMS_START + 62)
#define ITEM_MAGMA_EMBLEM (KEY_ITEMS_START + 63)
#define ITEM_OLD_SEA_MAP (KEY_ITEMS_START + 64)
#define ITEM_ODD_KEYSTONE (KEY_ITEMS_START + 65)
#define ITEM_GRACIDEA (KEY_ITEMS_START + 66)
#define ITEM_SHINY_CHARM (KEY_ITEMS_START + 67)
#define ITEM_OVAL_CHARM (KEY_ITEMS_START + 68)

#define KEY_ITEMS_END (ITEM_OVAL_CHARM)

#define GIMMICK_ITEMS_START (KEY_ITEMS_END + 1)
// Gimmicks Key Items
#define ITEM_MEGA_BRACELET (GIMMICK_ITEMS_START + 0)
#define ITEM_Z_RING (GIMMICK_ITEMS_START + 1)
#define ITEM_DYNAMAX_BAND (GIMMICK_ITEMS_START + 2)
#define ITEM_TERA_ORB (GIMMICK_ITEMS_START + 3)

#define GIMMICK_ITEMS_END (ITEM_TERA_ORB)

#define FOSSIL_ITEMS_START (GIMMICK_ITEMS_END + 1)
// Fossils
#define ITEM_ARMOR_FOSSIL (FOSSIL_ITEMS_START + 0)
#define ITEM_SKULL_FOSSIL (FOSSIL_ITEMS_START + 1)
#define ITEM_HELIX_FOSSIL (FOSSIL_ITEMS_START + 2)
#define ITEM_DOME_FOSSIL (FOSSIL_ITEMS_START + 3)
#define ITEM_COVER_FOSSIL (FOSSIL_ITEMS_START + 4)
#define ITEM_PLUME_FOSSIL (FOSSIL_ITEMS_START + 5)
#define ITEM_JAW_FOSSIL (FOSSIL_ITEMS_START + 6)
#define ITEM_SAIL_FOSSIL (FOSSIL_ITEMS_START + 7)
#define ITEM_ROOT_FOSSIL (FOSSIL_ITEMS_START + 8)
#define ITEM_CLAW_FOSSIL (FOSSIL_ITEMS_START + 9)
#define ITEM_FOSSILIZED_BIRD (FOSSIL_ITEMS_START + 10)
#define ITEM_FOSSILIZED_FISH (FOSSIL_ITEMS_START + 11)
#define ITEM_FOSSILIZED_DRAKE (FOSSIL_ITEMS_START + 12)
#define ITEM_FOSSILIZED_DINO (FOSSIL_ITEMS_START + 13)

#define FOSSIL_ITEMS_END (ITEM_FOSSILIZED_DINO)

#define POKEMON_SPECIFIC_ITEMS_START (FOSSIL_ITEMS_END + 1)
// Pokémon Specific items
#define ITEM_SOUL_DEW (POKEMON_SPECIFIC_ITEMS_START + 0)
#define ITEM_DEEP_SEA_TOOTH (POKEMON_SPECIFIC_ITEMS_START + 1)
#define ITEM_DEEP_SEA_SCALE (POKEMON_SPECIFIC_ITEMS_START + 2)
#define ITEM_LUCKY_PUNCH (POKEMON_SPECIFIC_ITEMS_START + 3)
#define ITEM_METAL_POWDER (POKEMON_SPECIFIC_ITEMS_START + 4)
#define ITEM_THICK_CLUB (POKEMON_SPECIFIC_ITEMS_START + 5)
#define ITEM_STICK (POKEMON_SPECIFIC_ITEMS_START + 6)
#define ITEM_LIGHT_BALL (POKEMON_SPECIFIC_ITEMS_START + 7)
#define ITEM_QUICK_POWDER (POKEMON_SPECIFIC_ITEMS_START + 8)

#define POKEMON_SPECIFIC_ITEMS_END (ITEM_QUICK_POWDER)

#define FORM_CHANGE_ITEMS_START (POKEMON_SPECIFIC_ITEMS_END + 1)
// Form change items
#define ITEM_RAINBOW_WING (FORM_CHANGE_ITEMS_START + 0)
#define ITEM_SILVER_WING (FORM_CHANGE_ITEMS_START + 1)
#define ITEM_ADAMANT_ORB (FORM_CHANGE_ITEMS_START + 2)
#define ITEM_LUSTROUS_ORB (FORM_CHANGE_ITEMS_START + 3)
#define ITEM_GRISEOUS_ORB (FORM_CHANGE_ITEMS_START + 4)
#define ITEM_CORNERSTONE_MASK (FORM_CHANGE_ITEMS_START + 5)
#define ITEM_WELLSPRING_MASK (FORM_CHANGE_ITEMS_START + 6)
#define ITEM_HEARTHFLAME_MASK (FORM_CHANGE_ITEMS_START + 7)
#define ITEM_RUSTED_SWORD (FORM_CHANGE_ITEMS_START + 8)
#define ITEM_RUSTED_SHIELD (FORM_CHANGE_ITEMS_START + 9)

#define FORM_CHANGE_ITEMS_END (ITEM_RUSTED_SHIELD)

#define MEMORIES_START (FORM_CHANGE_ITEMS_END + 1)
// Memories
#define ITEM_BUG_MEMORY (MEMORIES_START + 0)
#define ITEM_DARK_MEMORY (MEMORIES_START + 1)
#define ITEM_DRAGON_MEMORY (MEMORIES_START + 2)
#define ITEM_ELECTRIC_MEMORY (MEMORIES_START + 3)
#define ITEM_FAIRY_MEMORY (MEMORIES_START + 4)
#define ITEM_FIGHTING_MEMORY (MEMORIES_START + 5)
#define ITEM_FIRE_MEMORY (MEMORIES_START + 6)
#define ITEM_FLYING_MEMORY (MEMORIES_START + 7)
#define ITEM_GHOST_MEMORY (MEMORIES_START + 8)
#define ITEM_GRASS_MEMORY (MEMORIES_START + 9)
#define ITEM_GROUND_MEMORY (MEMORIES_START + 10)
#define ITEM_ICE_MEMORY (MEMORIES_START + 11)
#define ITEM_POISON_MEMORY (MEMORIES_START + 12)
#define ITEM_PSYCHIC_MEMORY (MEMORIES_START + 13)
#define ITEM_ROCK_MEMORY (MEMORIES_START + 14)
#define ITEM_STEEL_MEMORY (MEMORIES_START + 15)
#define ITEM_WATER_MEMORY (MEMORIES_START + 16)

#define MEMORIES_END (ITEM_WATER_MEMORY)

#define DRIVES_START (MEMORIES_END + 1)
// Drives
#define ITEM_DOUSE_DRIVE (DRIVES_START + 0)
#define ITEM_SHOCK_DRIVE (DRIVES_START + 1)
#define ITEM_BURN_DRIVE (DRIVES_START + 2)
#define ITEM_CHILL_DRIVE (DRIVES_START + 3)

#define DRIVES_END (ITEM_CHILL_DRIVE)

#define PLATES_START (DRIVES_END + 1)
// Plates
#define ITEM_INSECT_PLATE (PLATES_START + 0)
#define ITEM_DREAD_PLATE (PLATES_START + 1)
#define ITEM_DRACO_PLATE (PLATES_START + 2)
#define ITEM_ZAP_PLATE (PLATES_START + 3)
#define ITEM_PIXIE_PLATE (PLATES_START + 4)
#define ITEM_FIST_PLATE (PLATES_START + 5)
#define ITEM_FLAME_PLATE (PLATES_START + 6)
#define ITEM_SKY_PLATE (PLATES_START + 7)
#define ITEM_SPOOKY_PLATE (PLATES_START + 8)
#define ITEM_MEADOW_PLATE (PLATES_START + 9)
#define ITEM_EARTH_PLATE (PLATES_START + 10)
#define ITEM_ICICLE_PLATE (PLATES_START + 11)
#define ITEM_TOXIC_PLATE (PLATES_START + 12)
#define ITEM_MIND_PLATE (PLATES_START + 13)
#define ITEM_STONE_PLATE (PLATES_START + 14)
#define ITEM_IRON_PLATE (PLATES_START + 15)
#define ITEM_SPLASH_PLATE (PLATES_START + 16)
#define ITEM_LEGEND_PLATE (PLATES_START + 17)
#define ITEM_BLANK_PLATE (PLATES_START + 18)

#define PLATES_END (ITEM_BLANK_PLATE)

#define EVOLUTION_STONES_START (PLATES_END + 1)
// Evolution stones
#define ITEM_SUN_STONE (EVOLUTION_STONES_START + 0)
#define ITEM_MOON_STONE (EVOLUTION_STONES_START + 1)
#define ITEM_FIRE_STONE (EVOLUTION_STONES_START + 2)
#define ITEM_THUNDER_STONE (EVOLUTION_STONES_START + 3)
#define ITEM_WATER_STONE (EVOLUTION_STONES_START + 4)
#define ITEM_LEAF_STONE (EVOLUTION_STONES_START + 5)
#define ITEM_DAWN_STONE (EVOLUTION_STONES_START + 6)
#define ITEM_DUSK_STONE (EVOLUTION_STONES_START + 7)
#define ITEM_SHINY_STONE (EVOLUTION_STONES_START + 8)
#define ITEM_ICE_STONE (EVOLUTION_STONES_START + 9)

#define EVOLUTION_STONES_END (ITEM_ICE_STONE)

#define EVOLUTION_ITEMS_START (EVOLUTION_STONES_END + 1)
// Others
#define ITEM_KINGS_ROCK (EVOLUTION_ITEMS_START + 0)
#define ITEM_DRAGON_SCALE (EVOLUTION_ITEMS_START + 1)
#define ITEM_OVAL_STONE (EVOLUTION_ITEMS_START + 2)
#define ITEM_PROTECTOR (EVOLUTION_ITEMS_START + 3)
#define ITEM_ELECTIRIZER (EVOLUTION_ITEMS_START + 4)
#define ITEM_MAGMARIZER (EVOLUTION_ITEMS_START + 5)
#define ITEM_UP_GRADE (EVOLUTION_ITEMS_START + 6)
#define ITEM_DUBIOUS_DISC (EVOLUTION_ITEMS_START + 7)
#define ITEM_REAPER_CLOTH (EVOLUTION_ITEMS_START + 8)
#define ITEM_RAZOR_CLAW (EVOLUTION_ITEMS_START + 9)
#define ITEM_RAZOR_FANG (EVOLUTION_ITEMS_START + 10)
#define ITEM_PRISM_SCALE (EVOLUTION_ITEMS_START + 11)
#define ITEM_WHIPPED_DREAM (EVOLUTION_ITEMS_START + 12)
#define ITEM_SACHET (EVOLUTION_ITEMS_START + 13)
#define ITEM_SWEET_APPLE (EVOLUTION_ITEMS_START + 14)
#define ITEM_TART_APPLE (EVOLUTION_ITEMS_START + 15)
#define ITEM_CRACKED_POT (EVOLUTION_ITEMS_START + 16)
#define ITEM_CHIPPED_POT (EVOLUTION_ITEMS_START + 17)
#define ITEM_GALARICA_CUFF (EVOLUTION_ITEMS_START + 18)
#define ITEM_GALARICA_WREATH (EVOLUTION_ITEMS_START + 19)
#define ITEM_STRAWBERRY_SWEET (EVOLUTION_ITEMS_START + 20)
#define ITEM_LOVE_SWEET (EVOLUTION_ITEMS_START + 21)
#define ITEM_BERRY_SWEET (EVOLUTION_ITEMS_START + 22)
#define ITEM_CLOVER_SWEET (EVOLUTION_ITEMS_START + 23)
#define ITEM_FLOWER_SWEET (EVOLUTION_ITEMS_START + 24)
#define ITEM_STAR_SWEET (EVOLUTION_ITEMS_START + 25)
#define ITEM_RIBBON_SWEET (EVOLUTION_ITEMS_START + 26)
#define ITEM_LINKING_CORD (EVOLUTION_ITEMS_START + 27)
#define ITEM_AUSPICIOUS_ARMOR (EVOLUTION_ITEMS_START + 28)
#define ITEM_MALICIOUS_ARMOR (EVOLUTION_ITEMS_START + 29)
#define ITEM_LEADERS_CREST (EVOLUTION_ITEMS_START + 30)
#define ITEM_SYRUPY_APPLE (EVOLUTION_ITEMS_START + 31)
#define ITEM_UNREMARKABLE_TEACUP (EVOLUTION_ITEMS_START + 32)
#define ITEM_MASTERPIECE_TEACUP (EVOLUTION_ITEMS_START + 33)
#define ITEM_BLACK_AUGURITE (EVOLUTION_ITEMS_START + 34)
#define ITEM_PEAT_BLOCK (EVOLUTION_ITEMS_START + 35)
#define ITEM_SCROLL_OF_DARKNESS (EVOLUTION_ITEMS_START + 36)
#define ITEM_SCROLL_OF_WATERS (EVOLUTION_ITEMS_START + 37)
#define ITEM_METAL_ALLOY (EVOLUTION_ITEMS_START + 38)

#define EVOLUTION_ITEMS_END (ITEM_METAL_ALLOY)

#define PRIMAL_ORBS_START (EVOLUTION_ITEMS_END + 1)
// Primal Orbs
#define ITEM_RED_ORB (PRIMAL_ORBS_START + 0)
#define ITEM_BLUE_ORB (PRIMAL_ORBS_START + 1)

#define PRIMAL_ORBS_END (ITEM_BLUE_ORB)

#define MEGA_STONES_START (PRIMAL_ORBS_END + 1)
// Mega stones
#define ITEM_ABOMASITE (MEGA_STONES_START + 0)
#define ITEM_ABSOLITE (MEGA_STONES_START + 1)
#define ITEM_AERODACTYLITE (MEGA_STONES_START + 2)
#define ITEM_AGGRONITE (MEGA_STONES_START + 3)
#define ITEM_ALAKAZITE (MEGA_STONES_START + 4)
#define ITEM_ALTARIANITE (MEGA_STONES_START + 5)
#define ITEM_AMPHAROSITE (MEGA_STONES_START + 6)
#define ITEM_AUDINITE (MEGA_STONES_START + 7)
#define ITEM_BANETTITE (MEGA_STONES_START + 8)
#define ITEM_BEEDRILLITE (MEGA_STONES_START + 9)
#define ITEM_BLASTOISINITE (MEGA_STONES_START + 10)
#define ITEM_BLAZIKENITE (MEGA_STONES_START + 11)
#define ITEM_CAMERUPTITE (MEGA_STONES_START + 12)
#define ITEM_CHARIZARDITE_X (MEGA_STONES_START + 13)
#define ITEM_CHARIZARDITE_Y (MEGA_STONES_START + 14)
#define ITEM_DIANCITE (MEGA_STONES_START + 15)
#define ITEM_GALLADITE (MEGA_STONES_START + 16)
#define ITEM_GARCHOMPITE (MEGA_STONES_START + 17)
#define ITEM_GARDEVOIRITE (MEGA_STONES_START + 18)
#define ITEM_GENGARITE (MEGA_STONES_START + 19)
#define ITEM_GLALITITE (MEGA_STONES_START + 20)
#define ITEM_GYARADOSITE (MEGA_STONES_START + 21)
#define ITEM_HERACRONITE (MEGA_STONES_START + 22)
#define ITEM_HOUNDOOMINITE (MEGA_STONES_START + 23)
#define ITEM_KANGASKHANITE (MEGA_STONES_START + 24)
#define ITEM_LATIASITE (MEGA_STONES_START + 25)
#define ITEM_LATIOSITE (MEGA_STONES_START + 26)
#define ITEM_LOPUNNITE (MEGA_STONES_START + 27)
#define ITEM_LUCARIONITE (MEGA_STONES_START + 28)
#define ITEM_MANECTITE (MEGA_STONES_START + 29)
#define ITEM_MAWILITE (MEGA_STONES_START + 30)
#define ITEM_MEDICHAMITE (MEGA_STONES_START + 31)
#define ITEM_METAGROSSITE (MEGA_STONES_START + 32)
#define ITEM_MEWTWONITE_X (MEGA_STONES_START + 33)
#define ITEM_MEWTWONITE_Y (MEGA_STONES_START + 34)
#define ITEM_PIDGEOTITE (MEGA_STONES_START + 35)
#define ITEM_PINSIRITE (MEGA_STONES_START + 36)
#define ITEM_SABLENITE (MEGA_STONES_START + 37)
#define ITEM_SALAMENCITE (MEGA_STONES_START + 38)
#define ITEM_SCEPTILITE (MEGA_STONES_START + 39)
#define ITEM_SCIZORITE (MEGA_STONES_START + 40)
#define ITEM_SHARPEDONITE (MEGA_STONES_START + 41)
#define ITEM_SLOWBRONITE (MEGA_STONES_START + 42)
#define ITEM_STEELIXITE (MEGA_STONES_START + 43)
#define ITEM_SWAMPERTITE (MEGA_STONES_START + 44)
#define ITEM_TYRANITARITE (MEGA_STONES_START + 45)
#define ITEM_VENUSAURITE (MEGA_STONES_START + 46)
// Legends Z-A
#define ITEM_CLEFABLITE (MEGA_STONES_START + 47)
#define ITEM_VICTREEBELITE (MEGA_STONES_START + 48)
#define ITEM_STARMINITE (MEGA_STONES_START + 49)
#define ITEM_DRAGONINITE (MEGA_STONES_START + 50)
#define ITEM_MEGANIUMITE (MEGA_STONES_START + 51)
#define ITEM_FERALIGITE (MEGA_STONES_START + 52)
#define ITEM_SKARMORITE (MEGA_STONES_START + 53)
#define ITEM_FROSLASSITE (MEGA_STONES_START + 54)
#define ITEM_EMBOARITE (MEGA_STONES_START + 55)
#define ITEM_EXCADRITE (MEGA_STONES_START + 56)
#define ITEM_SCOLIPITE (MEGA_STONES_START + 57)
#define ITEM_SCRAFTINITE (MEGA_STONES_START + 58)
#define ITEM_EELEKTROSSITE (MEGA_STONES_START + 59)
#define ITEM_CHANDELURITE (MEGA_STONES_START + 60)
#define ITEM_CHESNAUGHTITE (MEGA_STONES_START + 61)
#define ITEM_DELPHOXITE (MEGA_STONES_START + 62)
#define ITEM_GRENINJITE (MEGA_STONES_START + 63)
#define ITEM_PYROARITE (MEGA_STONES_START + 64)
#define ITEM_FLOETTITE (MEGA_STONES_START + 65)
#define ITEM_MALAMARITE (MEGA_STONES_START + 66)
#define ITEM_BARBARACITE (MEGA_STONES_START + 67)
#define ITEM_DRAGALGITE (MEGA_STONES_START + 68)
#define ITEM_HAWLUCHANITE (MEGA_STONES_START + 69)
#define ITEM_ZYGARDITE (MEGA_STONES_START + 70)
#define ITEM_DRAMPANITE (MEGA_STONES_START + 71)
#define ITEM_FALINKSITE (MEGA_STONES_START + 72)
// Legends Z-A DLC
#define ITEM_HEATRANITE (MEGA_STONES_START + 73)
#define ITEM_DARKRANITE (MEGA_STONES_START + 74)
#define ITEM_ZERAORITE (MEGA_STONES_START + 75)
#define ITEM_RAICHUNITE_X (MEGA_STONES_START + 76)
#define ITEM_RAICHUNITE_Y (MEGA_STONES_START + 77)
#define ITEM_CHIMECHITE (MEGA_STONES_START + 78)
#define ITEM_ABSOLITE_Z (MEGA_STONES_START + 79)
#define ITEM_STARAPTITE (MEGA_STONES_START + 80)
#define ITEM_GARCHOMPITE_Z (MEGA_STONES_START + 81)
#define ITEM_LUCARIONITE_Z (MEGA_STONES_START + 82)
#define ITEM_GOLURKITE (MEGA_STONES_START + 83)
#define ITEM_MEOWSTICITE (MEGA_STONES_START + 84)
#define ITEM_CRABOMINITE (MEGA_STONES_START + 85)
#define ITEM_GOLISOPITE (MEGA_STONES_START + 86)
#define ITEM_MAGEARNITE (MEGA_STONES_START + 87)
#define ITEM_SCOVILLAINITE (MEGA_STONES_START + 88)
#define ITEM_BAXCALIBRITE (MEGA_STONES_START + 89)
#define ITEM_TATSUGIRINITE (MEGA_STONES_START + 90)
#define ITEM_GLIMMORANITE (MEGA_STONES_START + 91)

#define MEGA_STONES_END (ITEM_GLIMMORANITE)

#define Z_CRYSTALS_START (MEGA_STONES_END + 1)
// Z Crystals
#define ITEM_NORMALIUM_Z (Z_CRYSTALS_START + 0)
#define ITEM_FIGHTINIUM_Z (Z_CRYSTALS_START + 1)
#define ITEM_FLYINIUM_Z (Z_CRYSTALS_START + 2)
#define ITEM_POISONIUM_Z (Z_CRYSTALS_START + 3)
#define ITEM_GROUNDIUM_Z (Z_CRYSTALS_START + 4)
#define ITEM_ROCKIUM_Z (Z_CRYSTALS_START + 5)
#define ITEM_BUGINIUM_Z (Z_CRYSTALS_START + 6)
#define ITEM_GHOSTIUM_Z (Z_CRYSTALS_START + 7)
#define ITEM_STEELIUM_Z (Z_CRYSTALS_START + 8)
#define ITEM_FIRIUM_Z (Z_CRYSTALS_START + 9)
#define ITEM_WATERIUM_Z (Z_CRYSTALS_START + 10)
#define ITEM_GRASSIUM_Z (Z_CRYSTALS_START + 11)
#define ITEM_ELECTRIUM_Z (Z_CRYSTALS_START + 12)
#define ITEM_PSYCHIUM_Z (Z_CRYSTALS_START + 13)
#define ITEM_ICIUM_Z (Z_CRYSTALS_START + 14)
#define ITEM_DRAGONIUM_Z (Z_CRYSTALS_START + 15)
#define ITEM_DARKINIUM_Z (Z_CRYSTALS_START + 16)
#define ITEM_FAIRIUM_Z (Z_CRYSTALS_START + 17)
#define ITEM_ALORAICHIUM_Z (Z_CRYSTALS_START + 18)
#define ITEM_DECIDIUM_Z (Z_CRYSTALS_START + 19)
#define ITEM_EEVIUM_Z (Z_CRYSTALS_START + 20)
#define ITEM_INCINIUM_Z (Z_CRYSTALS_START + 21)
#define ITEM_KOMMONIUM_Z (Z_CRYSTALS_START + 22)
#define ITEM_LUNALIUM_Z (Z_CRYSTALS_START + 23)
#define ITEM_LYCANIUM_Z (Z_CRYSTALS_START + 24)
#define ITEM_MARSHADIUM_Z (Z_CRYSTALS_START + 25)
#define ITEM_MEWNIUM_Z (Z_CRYSTALS_START + 26)
#define ITEM_MIMIKIUM_Z (Z_CRYSTALS_START + 27)
#define ITEM_PIKANIUM_Z (Z_CRYSTALS_START + 28)
#define ITEM_PIKASHUNIUM_Z (Z_CRYSTALS_START + 29)
#define ITEM_PRIMARIUM_Z (Z_CRYSTALS_START + 30)
#define ITEM_SNORLIUM_Z (Z_CRYSTALS_START + 31)
#define ITEM_SOLGANIUM_Z (Z_CRYSTALS_START + 32)
#define ITEM_TAPUNIUM_Z (Z_CRYSTALS_START + 33)
#define ITEM_ULTRANECROZIUM_Z (Z_CRYSTALS_START + 34)

#define Z_CRYSTALS_END (ITEM_ULTRANECROZIUM_Z)

#define CUSTOM_ITEMS_START (Z_CRYSTALS_END + 1)
// Custom items made by me
#define ITEM_DEVIOLITE          (CUSTOM_ITEMS_START + 0)
#define ITEM_DRAGON_SLAYER      (CUSTOM_ITEMS_START + 1)
#define ITEM_DRAGON_BREATH      (CUSTOM_ITEMS_START + 2)
#define ITEM_MURAMASA           (CUSTOM_ITEMS_START + 3)
#define ITEM_POISON_KNIFE       (CUSTOM_ITEMS_START + 4)
#define ITEM_THIEF_GLOVES       (CUSTOM_ITEMS_START + 5)
#define ITEM_BONE_WAND          (CUSTOM_ITEMS_START + 6)
#define ITEM_SKULL_RING         (CUSTOM_ITEMS_START + 7)
#define ITEM_HEALING_STAFF      (CUSTOM_ITEMS_START + 8)
#define ITEM_STRONG_SHIELD      (CUSTOM_ITEMS_START + 9)
#define ITEM_MASAMUNE           (CUSTOM_ITEMS_START + 10)
#define ITEM_ASSASSIN_DAGGER    (CUSTOM_ITEMS_START + 11)
#define ITEM_SHACKLES           (CUSTOM_ITEMS_START + 12)
#define ITEM_WATERDROP_BROOCH   (CUSTOM_ITEMS_START + 13)
#define ITEM_SAKKAT             (CUSTOM_ITEMS_START + 14)
#define ITEM_FIREBLENDER        (CUSTOM_ITEMS_START + 15)
#define ITEM_ICE_FALCHION       (CUSTOM_ITEMS_START + 16)
#define ITEM_GOLDEN_HAMMER      (CUSTOM_ITEMS_START + 17)
#define ITEM_SAFETY_HELMET      (CUSTOM_ITEMS_START + 18)
#define ITEM_FROST_ORB          (CUSTOM_ITEMS_START + 19)
#define ITEM_INTRIGUING_STONE   (CUSTOM_ITEMS_START + 20)
#define ITEM_CONFUSE_ORB        (CUSTOM_ITEMS_START + 21)
#define ITEM_PARALYZE_ORB       (CUSTOM_ITEMS_START + 22)
#define ITEM_BLACK_TRIANGLE     (CUSTOM_ITEMS_START + 23)
#define ITEM_DNA_METEORITE      (CUSTOM_ITEMS_START + 24)
#define ITEM_MICROPHONE         (CUSTOM_ITEMS_START + 25)
#define ITEM_SUPPRESSION_HELMET (CUSTOM_ITEMS_START + 26)
#define ITEM_VACUUM_CLEANER     (CUSTOM_ITEMS_START + 27)

#define CUSTOM_ITEMS_END (ITEM_VACUUM_CLEANER)

// TMs/HMs
#define TM_START (CUSTOM_ITEMS_END + 1)

#define ITEM_TM01 (TM_START + 0)
#define ITEM_TM02 (TM_START + 1)
#define ITEM_TM03 (TM_START + 2)
#define ITEM_TM04 (TM_START + 3)
#define ITEM_TM05 (TM_START + 4)
#define ITEM_TM06 (TM_START + 5)
#define ITEM_TM07 (TM_START + 6)
#define ITEM_TM08 (TM_START + 7)
#define ITEM_TM09 (TM_START + 8)
#define ITEM_TM10 (TM_START + 9)
#define ITEM_TM11 (TM_START + 10)
#define ITEM_TM12 (TM_START + 11)
#define ITEM_TM13 (TM_START + 12)
#define ITEM_TM14 (TM_START + 13)
#define ITEM_TM15 (TM_START + 14)
#define ITEM_TM16 (TM_START + 15)
#define ITEM_TM17 (TM_START + 16)
#define ITEM_TM18 (TM_START + 17)
#define ITEM_TM19 (TM_START + 18)
#define ITEM_TM20 (TM_START + 19)
#define ITEM_TM21 (TM_START + 20)
#define ITEM_TM22 (TM_START + 21)
#define ITEM_TM23 (TM_START + 22)
#define ITEM_TM24 (TM_START + 23)
#define ITEM_TM25 (TM_START + 24)
#define ITEM_TM26 (TM_START + 25)
#define ITEM_TM27 (TM_START + 26)
#define ITEM_TM28 (TM_START + 27)
#define ITEM_TM29 (TM_START + 28)
#define ITEM_TM30 (TM_START + 29)
#define ITEM_TM31 (TM_START + 30)
#define ITEM_TM32 (TM_START + 31)
#define ITEM_TM33 (TM_START + 32)
#define ITEM_TM34 (TM_START + 33)
#define ITEM_TM35 (TM_START + 34)
#define ITEM_TM36 (TM_START + 35)
#define ITEM_TM37 (TM_START + 36)
#define ITEM_TM38 (TM_START + 37)
#define ITEM_TM39 (TM_START + 38)
#define ITEM_TM40 (TM_START + 39)
#define ITEM_TM41 (TM_START + 40)
#define ITEM_TM42 (TM_START + 41)
#define ITEM_TM43 (TM_START + 42)
#define ITEM_TM44 (TM_START + 43)
#define ITEM_TM45 (TM_START + 44)
#define ITEM_TM46 (TM_START + 45)
#define ITEM_TM47 (TM_START + 46)
#define ITEM_TM48 (TM_START + 47)
#define ITEM_TM49 (TM_START + 48)
#define ITEM_TM50 (TM_START + 49)
#define ITEM_TM51 (TM_START + 50)
#define ITEM_TM52 (TM_START + 51)
#define ITEM_TM53 (TM_START + 52)
#define ITEM_TM54 (TM_START + 53)
#define ITEM_TM55 (TM_START + 54)
#define ITEM_TM56 (TM_START + 55)
#define ITEM_TM57 (TM_START + 56)
#define ITEM_TM58 (TM_START + 57)
#define ITEM_TM59 (TM_START + 58)
#define ITEM_TM60 (TM_START + 59)
#define ITEM_TM61 (TM_START + 60)
#define ITEM_TM62 (TM_START + 61)
#define ITEM_TM63 (TM_START + 62)
#define ITEM_TM64 (TM_START + 63)
#define ITEM_TM65 (TM_START + 64)
#define ITEM_TM66 (TM_START + 65)
#define ITEM_TM67 (TM_START + 66)
#define ITEM_TM68 (TM_START + 67)
#define ITEM_TM69 (TM_START + 68)

#define NUM_TECHNICAL_MACHINES 69

#define HM_START (ITEM_TM69 + 1)

#define ITEM_HM01 (HM_START + 0)
#define ITEM_HM02 (HM_START + 1)
#define ITEM_HM03 (HM_START + 2)
#define ITEM_HM04 (HM_START + 3)
#define ITEM_HM05 (HM_START + 4)
#define ITEM_HM06 (HM_START + 5)
#define ITEM_HM07 (HM_START + 6)
#define ITEM_HM08 (HM_START + 7)

#define NUM_HIDDEN_MACHINES 8

#define ITEM_TM01_FOCUS_PUNCH ITEM_TM01
#define ITEM_TM02_DRAGON_CLAW ITEM_TM02
#define ITEM_TM03_WATER_PULSE ITEM_TM03
#define ITEM_TM04_CALM_MIND ITEM_TM04
#define ITEM_TM05_ROAR ITEM_TM05
#define ITEM_TM06_TOXIC ITEM_TM06
#define ITEM_TM07_HAIL ITEM_TM07
#define ITEM_TM08_BULK_UP ITEM_TM08
#define ITEM_TM09_BULLET_SEED ITEM_TM09
#define ITEM_TM10_HIDDEN_POWER ITEM_TM10
#define ITEM_TM11_SUNNY_DAY ITEM_TM11
#define ITEM_TM12_TAUNT ITEM_TM12
#define ITEM_TM13_ICE_BEAM ITEM_TM13
#define ITEM_TM14_BLIZZARD ITEM_TM14
#define ITEM_TM15_HYPER_BEAM ITEM_TM15
#define ITEM_TM16_LIGHT_SCREEN ITEM_TM16
#define ITEM_TM17_PROTECT ITEM_TM17
#define ITEM_TM18_RAIN_DANCE ITEM_TM18
#define ITEM_TM19_GIGA_DRAIN ITEM_TM19
#define ITEM_TM20_SAFEGUARD ITEM_TM20
#define ITEM_TM21_FRUSTRATION ITEM_TM21
#define ITEM_TM22_SOLARBEAM ITEM_TM22
#define ITEM_TM23_IRON_TAIL ITEM_TM23
#define ITEM_TM24_THUNDERBOLT ITEM_TM24
#define ITEM_TM25_THUNDER ITEM_TM25
#define ITEM_TM26_EARTHQUAKE ITEM_TM26
#define ITEM_TM27_RETURN ITEM_TM27
#define ITEM_TM28_DIG ITEM_TM28
#define ITEM_TM29_PSYCHIC ITEM_TM29
#define ITEM_TM30_SHADOW_BALL ITEM_TM30
#define ITEM_TM31_BRICK_BREAK ITEM_TM31
#define ITEM_TM32_DOUBLE_TEAM ITEM_TM32
#define ITEM_TM33_REFLECT ITEM_TM33
#define ITEM_TM34_SHOCK_WAVE ITEM_TM34
#define ITEM_TM35_FLAMETHROWER ITEM_TM35
#define ITEM_TM36_SLUDGE_BOMB ITEM_TM36
#define ITEM_TM37_SANDSTORM ITEM_TM37
#define ITEM_TM38_FIRE_BLAST ITEM_TM38
#define ITEM_TM39_ROCK_TOMB ITEM_TM39
#define ITEM_TM40_AERIAL_ACE ITEM_TM40
#define ITEM_TM41_TORMENT ITEM_TM41
#define ITEM_TM42_FACADE ITEM_TM42
#define ITEM_TM43_SECRET_POWER ITEM_TM43
#define ITEM_TM44_REST ITEM_TM44
#define ITEM_TM45_ATTRACT ITEM_TM45
#define ITEM_TM46_THIEF ITEM_TM46
#define ITEM_TM47_STEEL_WING ITEM_TM47
#define ITEM_TM48_SKILL_SWAP ITEM_TM48
#define ITEM_TM49_SNATCH ITEM_TM49
#define ITEM_TM50_OVERHEAT ITEM_TM50
#define ITEM_TM51_BRINE ITEM_TM51
#define ITEM_TM52_WORK_UP ITEM_TM52
#define ITEM_TM53_BUG_BUZZ ITEM_TM53
#define ITEM_TM54_HEAT_CRASH ITEM_TM54
#define ITEM_TM55_BODY_PRESS ITEM_TM55
#define ITEM_TM56_GEOGEYSER ITEM_TM56
#define ITEM_TM57_BURNING_TERRAIN ITEM_TM57
#define ITEM_TM58_NATURE_POWER ITEM_TM58
#define ITEM_TM59_NATURAL_GIFT ITEM_TM59
#define ITEM_TM60_TRI_ATTACK ITEM_TM60
#define ITEM_TM61_WILD_CHARGE ITEM_TM61
#define ITEM_TM62_FROZEN_TERRAIN ITEM_TM62
#define ITEM_TM63_SANDY_TERRAIN ITEM_TM63
#define ITEM_TM64_SWAMPY_TERRAIN ITEM_TM64
#define ITEM_TM65_FOG ITEM_TM65
#define ITEM_TM66_HEADBUTT ITEM_TM66
#define ITEM_TM67_ZAP_CANNON ITEM_TM67
#define ITEM_TM68_CHILLING_WATER ITEM_TM68
#define ITEM_TM69_STONE_EDGE ITEM_TM69

//HMs
#define ITEM_HM01_CUT ITEM_HM01
#define ITEM_HM02_FLY ITEM_HM02
#define ITEM_HM03_SURF ITEM_HM03
#define ITEM_HM04_STRENGTH ITEM_HM04
#define ITEM_HM05_FLASH ITEM_HM05
#define ITEM_HM06_ROCK_SMASH ITEM_HM06
#define ITEM_HM07_WATERFALL ITEM_HM07
#define ITEM_HM08_DIVE ITEM_HM08

#define ITEMS_COUNT (ITEM_HM08_DIVE + 1)
#define ITEM_FIELD_ARROW ITEMS_COUNT

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId)(((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId)((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF

#define MAX_BAG_ITEM_CAPACITY  999
#define MAX_PC_ITEM_CAPACITY   999
#define MAX_BERRY_CAPACITY     999

#define BAG_ITEM_CAPACITY_DIGITS 3
#define BERRY_CAPACITY_DIGITS 3
#define MAX_ITEM_DIGITS BERRY_CAPACITY_DIGITS

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL        0
#define ITEM_USE_PARTY_MENU  1
#define ITEM_USE_FIELD       2
#define ITEM_USE_PBLOCK_CASE 3
#define ITEM_USE_BAG_MENU    4 // No exit callback, stays in bag menu

// Item battle usage IDs (only checked to see if nonzero)
#define ITEM_B_USE_MEDICINE 1
#define ITEM_B_USE_OTHER    2

// Pokemon natures
#define NATURE_HARDY    0
#define NATURE_LONELY   1
#define NATURE_BRAVE    2
#define NATURE_ADAMANT  3
#define NATURE_NAUGHTY  4
#define NATURE_BOLD     5
#define NATURE_DOCILE   6
#define NATURE_RELAXED  7
#define NATURE_IMPISH   8
#define NATURE_LAX      9
#define NATURE_TIMID    10
#define NATURE_HASTY    11
#define NATURE_SERIOUS  12
#define NATURE_JOLLY    13
#define NATURE_NAIVE    14
#define NATURE_MODEST   15
#define NATURE_MILD     16
#define NATURE_QUIET    17
#define NATURE_BASHFUL  18
#define NATURE_RASH     19
#define NATURE_CALM     20
#define NATURE_GENTLE   21
#define NATURE_SASSY    22
#define NATURE_CAREFUL  23
#define NATURE_QUIRKY   24
#define NUM_NATURES     25

#endif  // GUARD_CONSTANTS_ITEMS_H
