PacifidlogIsland_House1_MapScripts::
	.byte 0

PacifidlogIsland_House1_EventScript_OldBoy::
	msgbox PacifidlogIsland_House1_Text_OldBoy, MSGBOX_NPC
	end

PacifidlogIsland_House1_Text_OldBoy:
	.string "Sometimes, a Pokémon descent\n"
	.string "from the sky here in this island…\l"
	.string "…\l"
	.string "…\p"
	.string "No, I'm not talking about the\n"
	.string "legendary flying dragon…\p"
	.string "I'm talking about a phoenix\n"
	.string "like Pokémon.\l"
	.string "Once every ten years, this Pokémon\l"
	.string "comes to this island, and all people\l"
	.string "from Pacifidlog come here to this\l"
	.string "island to commemorate and feast!$"
